import{createSession,TaskManager,TASK_SEQUENCE,eyeTrackingService}from'./taskManager.js';import{entrypointFor}from'./taskAdapters.js';
const root=document.querySelector('#app'),debug=new URLSearchParams(location.search).get('debug')==='1';let manager,frame,timer;const log=(e,d={})=>console.info(`[MASTER] ${e}`,d),render=h=>root.innerHTML=h;
const scoreOf=(id,r={})=>{if(id.startsWith('T01-')){const v=[r.emotion?.score,r.cause?.score].filter(x=>typeof x==='number');return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}if(id==='T05'){const v=[r.T05A?.score,r.T05B?.score].filter(x=>typeof x==='number');return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}for(const k of ['score','task_score','total_score','T02_total_score','T03_score','T04_score','T05_score','T06_score','T07_score','T08_total_score','T09_score','T10_score'])if(typeof r[k]==='number')return r[k];return null};
function finishCurrent(id,r={}){const result={...r,score:scoreOf(id,r),score_status:scoreOf(id,r)==null?'score_missing':'available'};manager.finishTask(id,result);manager.goToNextTask()}
function welcome(){render(`<main class="shell"><h1>特殊儿童社会情感学习（SEL）数字化测评</h1><button id="start">开始测评</button>${debug?`<details open><summary>开发跳转</summary><select id="jump">${TASK_SEQUENCE.map(x=>`<option>${x}</option>`).join('')}</select><button id="go">跳转</button></details>`:''}</main>`);document.querySelector('#start').onclick=info;if(debug)document.querySelector('#go').onclick=()=>{manager=new TaskManager(createSession({id:'DEBUG',age:'',gender:''}),{onStart:loadTask,onComplete:complete});manager.startTask(document.querySelector('#jump').value)}}
function info(){render('<main class="shell"><h2>儿童基本信息</h2><form id="f"><label>儿童编号<input name="id" required></label><label>年龄<input name="age" required></label><label>性别<select name="gender" required><option value="">请选择</option><option>男</option><option>女</option><option>其他</option></select></label><button>进入正式任务</button></form></main>');document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);manager=new TaskManager(createSession({id:f.get('id'),age:f.get('age'),gender:f.get('gender')}),{onStart:loadTask,onComplete:complete});manager.startTask(TASK_SEQUENCE[0])}}
function loadTask(id){clearInterval(timer);eyeTrackingService.start(['T05','T06','T07','T08'].includes(id)?id:null);const url=entrypointFor(id);render(`<main class="task-shell"><div class="task-meta"><strong>当前任务：${id}</strong><span>第 ${manager.currentTaskIndex+1}/${TASK_SEQUENCE.length} 项</span></div><iframe class="task-frame" src="${url}" title="${id}" allow="autoplay; microphone"></iframe><p id="err" class="error" hidden>任务加载失败，请查看 MASTER 日志。</p></main>`);frame=document.querySelector('iframe');let done=false;window.__activeTaskComplete=(r={})=>{if(done)return;done=true;log('TASK_COMPLETE',{task_id:id});finishCurrent(id,r)};frame.onload=()=>{log('IFRAME_LOADED',{task_id:id});if(!url.startsWith('http://127.0.0.1:808'))timer=setInterval(()=>probe(id),500)};frame.onerror=()=>{document.querySelector('#err').hidden=false;log('PAGE_LOAD_FAILED',{task_id:id})}}
function probe(id){try{const d=frame.contentDocument;if(!d)return;const text=d.body?.innerText||'';const end=id==='T04'?d.querySelector('.done'):id==='T05'?d.querySelector('.end'):id==='T06'?d.documentElement.dataset.completed==='true':id==='T07'?d.querySelector('.complete-panel'):id==='T09'?d.querySelector('.done-screen'):id==='T10'?d.querySelector('.result'):id==='T03'?/practice complete|任务完成|assessment complete/i.test(text):false;if(end){let r={integration:'dom-completion-probe'};try{for(const k of ['T04_task_data','T05_latest','sel_assessment_T06_records','SEL_T07_result']){const v=d.defaultView.localStorage.getItem(k);if(v)r=JSON.parse(v)}}catch{}window.__activeTaskComplete(r)}}catch(e){log('PROBE_ERROR',{task_id:id,error:e.message})}}
window.addEventListener('message',e=>{const d=e.data||{},type=d.type||'';log('POST_MESSAGE_RECEIVED',{type,task_id:d.taskId||d.task_id});if(type==='SEL_T01_COMPLETE')window.__activeTaskComplete?.(d.payload||{});else if(['TASK_COMPLETE','SEL_ASSESSMENT_COMPLETE','t08complete'].includes(type))window.__activeTaskComplete?.(d.result||d.payload||d.detail||{})});
function radar(){return`<svg class="radar" viewBox="0 0 360 360" aria-label="五维能力雷达图">${[1,2,3,4,5].map(n=>`<polygon points="${[0,1,2,3,4].map(i=>{const a=-Math.PI/2+i*2*Math.PI/5;return`${180+Math.cos(a)*30*n},${180+Math.sin(a)*30*n}`}).join(' ')}" fill="none" stroke="#d9e2ea"/>`).join('')}<text x="180" y="180" text-anchor="middle">数据核查后生成</text></svg>`}
function complete(s){eyeTrackingService.stop();const slots=TASK_SEQUENCE.map(id=>{const task=s.tasks[id.replace('-','_')]||{},score=task.score??null;return{id,task,score,status:task.score_status||'score_missing'}}),vals=slots.filter(x=>typeof x.score==='number').map(x=>x.score),total=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,json={participant:s.participant,session:s.session,tasks:s.tasks,dimension_scores:{self_management:null,emotion_understanding:null,relationship_skills:null,problem_solving:null,responsibility:null},total_score:total};render(`<main class="completion"><h2>测评完成</h2><p>儿童编号：${s.participant.id}</p><h3>总体结果</h3><p>总分：${total??'score_missing'}</p><div class="radar-wrap">${radar()}<div>${['自我管理','情绪理解','关系技能','问题解决','责任选择'].map(x=>`<p>${x}：score_missing（待维度映射）</p>`).join('')}</div></div><h3>任务完成情况</h3><ul>${slots.map(x=>`<li>${x.id}：已完成；得分 ${x.score??'score_missing'}</li>`).join('')}</ul><button id="export">导出本次测评数据</button><small>session_id 已保存在导出 JSON 中</small></main>`);document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(json,null,2)],{type:'application/json'}));a.download=`SEL_${s.participant.id||'session'}.json`;a.click()}}
welcome();
