import{createSession,TaskManager,TASK_SEQUENCE,eyeTrackingService}from'./taskManager.js';import{entrypointFor}from'./taskAdapters.js';
const root=document.querySelector('#app'),debug=new URLSearchParams(location.search).get('debug')==='1';let manager,frame,timer;const log=(e,d={})=>console.info(`[MASTER] ${e}`,d),render=h=>root.innerHTML=h;
const scoreOf=(id,r={})=>{if(id.startsWith('T01-')){const v=[r.emotion?.score,r.cause?.score].filter(x=>typeof x==='number');return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}if(id==='T05'){const v=[r.T05A?.score,r.T05B?.score].filter(x=>typeof x==='number');return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}for(const k of ['score','task_score','total_score','T02_total_score','T03_score','T04_score','T05_score','T06_score','T07_score','T08_total_score','T09_score','T10_score'])if(typeof r[k]==='number')return r[k];return null};
let pendingDebugTask='';
function finishCurrent(id,r={}){const result={...r,score:scoreOf(id,r),score_status:scoreOf(id,r)==null?'score_missing':'available'};manager.finishTask(id,result);if(debug){localStorage.setItem('sel.master.session',JSON.stringify(manager.session));pendingDebugTask=id;window.dispatchEvent(new CustomEvent('MASTER_TASK_SAVED',{detail:{taskId:id,result:manager.session.tasks[id.replace('-', '_')]}}));document.querySelector('.master-pause-overlay')?.remove();document.querySelector('.master-pause')?.remove();reviewPage();return}manager.goToNextTask()}
function welcome(){render(`<main class="shell"><h1>特殊儿童社会情感学习（SEL）数字化测评</h1><button id="start">开始测评</button>${debug?`<details open><summary>开发跳转</summary><select id="jump">${TASK_SEQUENCE.map(x=>`<option>${x}</option>`).join('')}</select><button id="go">跳转</button></details>`:''}</main>`);document.querySelector('#start').onclick=info;if(debug)document.querySelector('#go').onclick=()=>{manager=new TaskManager(createSession({id:'DEBUG',age:'',gender:''}),{onStart:loadTask,onComplete:complete});manager.startTask(document.querySelector('#jump').value)}}
function info(){render('<main class="shell"><h2>儿童基本信息</h2><form id="f"><label>儿童编号<input name="id" required></label><label>年龄<input name="age" required></label><label>性别<select name="gender" required><option value="">请选择</option><option>男</option><option>女</option><option>其他</option></select></label><button>进入正式任务</button></form></main>');document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);manager=new TaskManager(createSession({id:f.get('id'),age:f.get('age'),gender:f.get('gender')}),{onStart:loadTask,onComplete:complete});manager.startTask(TASK_SEQUENCE[0])}}
async function loadTask(id){
  clearInterval(timer); window.dispatchEvent(new CustomEvent('MASTER_TASK_STARTED',{detail:{taskId:id}}));
  eyeTrackingService.start(['T05','T06','T07','T08'].includes(id)?id:null);
  const url=entrypointFor(id),deferFrame=id==='T02',deferT03=id==='T03';
  const body=deferFrame||deferT03?'<div class="task-frame-slot"></div>':`<iframe class="task-frame" src="${url}" title="${id}" allow="autoplay; microphone"></iframe>`;
  render(`<main class="task-shell"><div class="task-meta"><strong>当前任务：${id}</strong><span>第 ${manager.currentTaskIndex+1}/${TASK_SEQUENCE.length} 项</span></div>${body}<p id="taskPreparing" class="muted" ${deferT03?'':'hidden'}>任务准备中…</p><p id="err" class="error" hidden>任务加载失败。主试可重新加载或跳过并记录失败。</p><div class="task-recovery"><button id="retryTask">重新加载当前任务</button><button id="skipFailedTask">跳过并记录 task_failed</button></div></main>`);
  frame=deferFrame||deferT03?null:document.querySelector('iframe'); let done=false,frameCreated=!!frame;
  window.__activeTaskComplete=(r={})=>{if(done)return;done=true;log('TASK_COMPLETE',{task_id:id});finishCurrent(id,r)};
  document.querySelector('#retryTask').onclick=()=>loadTask(id);
  document.querySelector('#skipFailedTask').onclick=()=>{if(done)return;done=true;manager.finishTask(id,{task_failed:true,score_status:'score_missing',error:'proctor_skipped_after_load_failure'});manager.goToNextTask()};
  const fail=(reason)=>{document.querySelector('#taskPreparing')?.setAttribute('hidden','');const err=document.querySelector('#err');if(err){err.hidden=false;err.textContent=`任务加载失败：${reason}`};log('PAGE_LOAD_FAILED',{task_id:id,error:reason})};
  const bindFrame=()=>{frame.onload=()=>{document.querySelector('#taskPreparing')?.setAttribute('hidden','');log('iframe_load',{task_id:id,src:frame.src});if(!url.startsWith('http://127.0.0.1:808'))timer=setInterval(()=>probe(id),500)};frame.onerror=()=>fail('iframe_error')};
  const createDeferredFrame=()=>{if(frameCreated||done)return frame;const slot=document.querySelector('.task-frame-slot');if(!slot)return fail('iframe_slot_missing');frameCreated=true;frame=document.createElement('iframe');frame.className='task-frame';frame.src=url;frame.title=id;frame.setAttribute('allow','autoplay; microphone');bindFrame();slot.replaceWith(frame);log('iframe_created',{task_id:id,src:frame.src});return frame};
  if(deferFrame)window.addEventListener('MASTER_INTRO_COMPLETE',createDeferredFrame,{once:true});
  else if(deferT03){try{const health=await fetch('/api/v1/health',{cache:'no-store'});if(!health.ok)throw Error(`health_${health.status}`);createDeferredFrame()}catch(error){fail(error.message)}}
  else{bindFrame();log('iframe_created',{task_id:id,src:frame.src})}
}
function probe(id){try{const d=frame.contentDocument;if(!d)return;const text=d.body?.innerText||'';const end=id==='T04'?d.querySelector('.done'):id==='T05'?d.querySelector('.end'):id==='T06'?d.documentElement.dataset.completed==='true':id==='T07'?d.querySelector('.complete-panel'):id==='T09'?d.querySelector('.done-screen'):id==='T10'?d.querySelector('.result'):id==='T03'?/practice complete|任务完成|assessment complete/i.test(text):false;if(end){let r={integration:'dom-completion-probe'};try{for(const k of ['T04_task_data','T05_latest','sel_assessment_T06_records','SEL_T07_result']){const v=d.defaultView.localStorage.getItem(k);if(v)r=JSON.parse(v)}}catch{}window.__activeTaskComplete(r)}}catch(e){log('PROBE_ERROR',{task_id:id,error:e.message})}}
window.addEventListener('message',e=>{const d=e.data||{},type=d.type||'';log('POST_MESSAGE_RECEIVED',{type,task_id:d.taskId||d.task_id});if(type==='EYE_TRACKING_AOI'&&window.EyeTracking)EyeTracking.setAOIRegions(d.regions);if(type==='EYE_TRACKING_START'&&window.EyeTracking){try{const r=frame?.getBoundingClientRect();EyeTracking.startWindow({taskId:d.task_id,sceneId:d.scene_id,task_viewport:r?{x:r.left,y:r.top,width:r.width,height:r.height}:d.task_viewport})}catch(error){console.warn('[MASTER] eye_tracking_status=start_failed',error)}}if(type==='EYE_TRACKING_STOP'&&window.EyeTracking){EyeTracking.stopWindow().catch(error=>console.warn('[MASTER] eye_tracking_status=save_failed',error))}if(type==='SEL_T01_COMPLETE')window.__activeTaskComplete?.(d.payload||{});else if(['TASK_COMPLETE','SEL_ASSESSMENT_COMPLETE','t08complete'].includes(type))window.__activeTaskComplete?.(d.result||d.payload||d.detail||{})});
function radar(){return`<svg class="radar" viewBox="0 0 360 360" aria-label="五维能力雷达图">${[1,2,3,4,5].map(n=>`<polygon points="${[0,1,2,3,4].map(i=>{const a=-Math.PI/2+i*2*Math.PI/5;return`${180+Math.cos(a)*30*n},${180+Math.sin(a)*30*n}`}).join(' ')}" fill="none" stroke="#d9e2ea"/>`).join('')}<text x="180" y="180" text-anchor="middle">数据核查后生成</text></svg>`}
function complete(s){eyeTrackingService.stop();const slots=TASK_SEQUENCE.map(id=>{const task=s.tasks[id.replace('-','_')]||{},score=task.score??null;return{id,task,score,status:task.score_status||'score_missing'}}),vals=slots.filter(x=>typeof x.score==='number').map(x=>x.score),total=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,json={participant:s.participant,session:s.session,tasks:s.tasks,dimension_scores:{self_management:null,emotion_understanding:null,relationship_skills:null,problem_solving:null,responsibility:null},total_score:total};render(`<main class="completion"><h2>测评完成</h2><p>儿童编号：${s.participant.id}</p><h3>总体结果</h3><p>总分：${total??'score_missing'}</p><div class="radar-wrap">${radar()}<div>${['自我管理','情绪理解','关系技能','问题解决','责任选择'].map(x=>`<p>${x}：score_missing（待维度映射）</p>`).join('')}</div></div><h3>任务完成情况</h3><ul>${slots.map(x=>`<li>${x.id}：已完成；得分 ${x.score??'score_missing'}</li>`).join('')}</ul><button id="export">导出本次测评数据</button><small>session_id 已保存在导出 JSON 中</small></main>`);document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(json,null,2)],{type:'application/json'}));a.download=`SEL_${s.participant.id||'session'}.json`;a.click()}}
function reviewPage(){if(!debug)return;const session=manager?.session||createSession({id:'暂无',age:'',gender:''});const rows=TASK_SEQUENCE.map(id=>{const key=id.replace('-','_'),r=session.tasks[key]||{};return{id,r}});const field=(label,value)=>`<div class="review-field"><b>${label}</b><span>${value==null||value===''?'暂无数据':String(value)}</span></div>`;const taskCard=({id,r})=>{const records=r.records||r.responses||r.speech_records||r.records||[];const score=r.score??r.task_score??r.total_score??r[`${id}_score`]??null;return`<article class="review-card"><h3>${id}</h3><div class="review-summary">${field('任务总分',score)}${field('score_status',r.score_status|| (score==null?'score_missing':'available'))}${field('计分公式',r.scoring_formula||'按任务原始结果保存，不在此页重新计分')}</div><div class="review-records">${Array.isArray(records)&&records.length?records.map((x,i)=>`<div class="review-record"><strong>记录 ${i+1}</strong>${Object.entries(x).filter(([k])=>!['blob'].includes(k)).map(([k,v])=>field(k,typeof v==='object'?JSON.stringify(v):v)).join('')}</div>`).join(''):'<p>暂无数据</p>'}</div><details><summary>查看原始JSON</summary><pre>${JSON.stringify(r,null,2)}</pre></details></article>`};render(`<main class="review-page"><header><h1>主试计分核对</h1><p>仅开发模式可见；本页只读取真实保存结果，不重新计分。</p><button id="backReview">返回</button></header><nav class="review-tabs">${TASK_SEQUENCE.map(id=>`<button data-task="${id}">${id}</button>`).join('')}</nav><section id="reviewContent">${rows.map(taskCard).join('')}</section></main>`);document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.task)?.scrollIntoView({behavior:'smooth'})});document.querySelector('#backReview').onclick=welcome}
if(debug){reviewPage=function(){const session=manager?.session||createSession({id:'暂无',age:'',gender:''});const id=pendingDebugTask||TASK_SEQUENCE[0],key=id.replace('-','_'),r=session.tasks[key]||{},score=r.score??r.task_score??r.total_score??null;const value=v=>v==null||v===''?'暂无数据':String(v);const records=r.records||r.responses||r.speech_records||[];const fields=[['任务总分',score],['score_status',r.score_status||(score==null?'score_missing':'available')],['完成状态',r.end_time?'已完成':'未完成'],['完成时间',r.end_time],['计分公式',r.scoring_formula||'按任务原始结果保存，不在此页重新计分']].map(([a,b])=>`<div class="review-field"><b>${a}</b><span>${value(b)}</span></div>`).join('');const recordHtml=Array.isArray(records)&&records.length?records.map((x,i)=>`<div class="review-record"><strong>记录 ${i+1}</strong>${Object.entries(x).filter(([k])=>k!=='blob').map(([a,b])=>`<div class="review-field"><b>${a}</b><span>${value(typeof b==='object'?JSON.stringify(b):b)}</span></div>`).join('')}</div>`).join(''):'<p>暂无记录</p>';render(`<main class="review-page"><header><h1>${id} 计分结果</h1><p>仅开发模式可见；本页只读取当前任务真实保存结果，不重新计分。</p></header><article class="review-card"><div class="review-summary">${fields}</div><div class="review-records">${recordHtml}</div><details><summary>查看原始JSON</summary><pre>${JSON.stringify(r,null,2)}</pre></details></article><div class="review-actions"><button id="continueTask">继续下一任务</button><button id="retryTask">重新测试当前任务</button><button id="allReview">返回Debug控制台</button></div></main>`);document.querySelector('#continueTask').onclick=()=>{pendingDebugTask='';manager.goToNextTask()};document.querySelector('#retryTask').onclick=()=>{manager.session.tasks[key]={};pendingDebugTask='';manager.startTask(id)};document.querySelector('#allReview').onclick=()=>{pendingDebugTask='';welcome()}}}
welcome();
if(debug){const d=document.querySelector('details');if(d){const b=document.createElement('button');b.textContent='主试计分核对';b.onclick=reviewPage;d.appendChild(b)}}
