const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const t01VoiceService = require('./t01VoiceService');
const database = require('./database/store');
const ROOT = __dirname;
const PORT = Number(process.env.PORT || 4170);
const HOST = process.env.HOST || '0.0.0.0';
const children = [];
const log = (event, data = {}) => console.log(`[MASTER] ${new Date().toISOString()} ${event}`, JSON.stringify(data));
function loadDotEnv() { const file = path.join(ROOT, '.env'); if (!fs.existsSync(file)) return; for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, ''); } }
loadDotEnv();
function child(label, command, args, cwd, env = {}) { log('SERVICE_START', { service: label, command, args }); const childProcess = spawn(command, args, { cwd: path.join(ROOT, cwd), env: { ...process.env, ...env }, stdio: 'inherit' }); childProcess.on('error', (error) => log('SERVICE_START_FAILED', { service: label, error: error.message })); childProcess.on('exit', (code, signal) => { if (code !== 0) log('SERVICE_EXITED', { service: label, code, signal }); }); children.push(childProcess); }
child('T02', process.execPath, ['server.js'], 'tasks/T02', { PORT: '8081' });
child('T08', process.execPath, ['server.js'], 'tasks/T08', { PORT: '8082' });
child('T03', process.env.SEL_PYTHON || (process.platform === 'win32' ? 'python' : 'python3'), ['-m', 'uvicorn', 'backend.app.main:app', '--host', '127.0.0.1', '--port', '8000'], 'tasks/T03', { SEL_ASSET_PREFIX: '/tasks/T03/frontend/dist/assets/tasks/T03' });
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.mp3': 'audio/mpeg', '.mp4': 'video/mp4', '.wav': 'audio/wav', '.webm': 'audio/webm', '.svg': 'image/svg+xml' };
function readBody(req){return new Promise((resolve,reject)=>{const chunks=[];req.on('data',chunk=>chunks.push(chunk));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
function proxyRequest(req,res,port,prefix){const targetPath=req.url.startsWith(prefix)?req.url.slice(prefix.length)||'/':req.url;const proxy=http.request({hostname:'127.0.0.1',port,path:targetPath,method:req.method,headers:{...req.headers,host:`127.0.0.1:${port}`}},upstream=>{res.writeHead(upstream.statusCode||502,upstream.headers);upstream.pipe(res)});proxy.on('error',error=>{log('SUBSERVICE_PROXY_FAILED',{port,error:error.message});if(!res.headersSent)res.writeHead(502);res.end('Subservice unavailable')});req.pipe(proxy)}
function waitForT03Ready(attempts=12){return new Promise(resolve=>{const check=(left)=>{const h=http.get({hostname:'127.0.0.1',port:8000,path:'/api/v1/health',timeout:1200},upstream=>{upstream.resume();if(upstream.statusCode===200)return resolve(true);if(left<=1)return resolve(false);setTimeout(()=>check(left-1),500)});h.on('error',()=>{if(left<=1)return resolve(false);setTimeout(()=>check(left-1),500)});h.on('timeout',()=>h.destroy())};check(attempts)})}
async function proxyT03(req,res){const body=await readBody(req);if(!(await waitForT03Ready())){log('T03_NOT_READY',{method:req.method,path:req.url});res.writeHead(503,{'Content-Type':'application/json','Retry-After':'2'});return res.end(JSON.stringify({detail:'T03 task service is preparing'}))}const target=req.url;const maxAttempts=req.method==='GET'?3:1;let attempt=0;const send=()=>{attempt++;const proxy=http.request({hostname:'127.0.0.1',port:8000,path:target,method:req.method,headers:{...req.headers,host:'127.0.0.1:8000','content-length':body.length}},upstream=>{res.writeHead(upstream.statusCode||502,upstream.headers);upstream.pipe(res)});proxy.on('error',error=>{log('T03_API_PROXY_FAILED',{method:req.method,path:req.url,attempt,error:error.message});if(!res.headersSent&&attempt<maxAttempts)return setTimeout(send,400*attempt);if(!res.headersSent){res.writeHead(503,{'Content-Type':'application/json','Retry-After':'2'});res.end(JSON.stringify({detail:'T03 task service temporarily unavailable'}))}});proxy.end(body)};send()}
function serveMasterFile(req,res,file){const stat=fs.statSync(file),ext=path.extname(file).toLowerCase(),headers={'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':file.includes(`${path.sep}assets${path.sep}`)||['.mp3','.mp4','.wav','.png','.jpg','.jpeg'].includes(ext)?'public, max-age=604800':'no-cache','Accept-Ranges':'bytes'},match=String(req.headers.range||'').match(/^bytes=(\d*)-(\d*)$/);if(match){const start=match[1]?Number(match[1]):0,end=match[2]?Math.min(Number(match[2]),stat.size-1):stat.size-1;if(start>end||start>=stat.size){res.writeHead(416,{'Content-Range':`bytes */${stat.size}`});return res.end()}res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Content-Length':end-start+1});return fs.createReadStream(file,{start,end}).pipe(res)}res.writeHead(200,{...headers,'Content-Length':stat.size});fs.createReadStream(file).pipe(res)}
const server = http.createServer(async (req, res) => { const url = decodeURIComponent((req.url || '/').split('?')[0]); if (url === '/health') { res.writeHead(200, { 'Content-Type': 'application/json' }); return res.end(JSON.stringify({ status: 'ok', service: 'MASTER', database: database.configured() ? 'configured' : 'not_configured' })); } if (url === '/api/database/save' && req.method === 'POST') { try { const payload = JSON.parse((await readBody(req)).toString('utf8') || '{}'); const result = await database.save(payload); res.writeHead(200, { 'Content-Type': 'application/json' }); return res.end(JSON.stringify(result)); } catch (error) { log('DATABASE_SAVE_FAILED', { error: error.message }); res.writeHead(500, { 'Content-Type': 'application/json' }); return res.end(JSON.stringify({ ok: false, error: 'database_save_failed' })); } } if (url.startsWith('/task/T02/')) return proxyRequest(req,res,8081,'/task/T02'); if (url.startsWith('/task/T08/')) return proxyRequest(req,res,8082,'/task/T08'); if ((url === '/api/t01/voice-score' || url === '/api/t01/text-score') && req.method === 'POST') return t01VoiceService.score(req, res); if (url.startsWith('/api/v1/')) return proxyT03(req,res); let fileUrl = url === '/' ? '/index.html' : url; let file; if (fileUrl.startsWith('/assets/T07/')) file = path.join(ROOT, 'tasks/T07/dist/assets/T07', fileUrl.slice('/assets/T07/'.length)); else if (fileUrl.startsWith('/assets/index-')) file = path.join(ROOT, 'tasks/T07/dist/assets', fileUrl.slice('/assets/'.length)); else file = path.resolve(ROOT, `.${fileUrl}`); if (!file.startsWith(path.resolve(ROOT)) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { log('PAGE_LOAD_FAILED', { url: fileUrl, status: 404 }); res.writeHead(404); return res.end('Not found'); } serveMasterFile(req,res,file); });
async function boot() { if (database.configured()) { try { await database.initSchema(); log('DATABASE_SCHEMA_READY'); } catch (error) { log('DATABASE_SCHEMA_FAILED', { error: error.message }); } } server.listen(PORT, HOST, () => log('MASTER_READY', { port: PORT, host: HOST, database: database.configured() })); }
boot();
const stop = () => { children.forEach((childProcess) => childProcess.kill()); server.close(() => process.exit(0)); };
process.on('SIGINT', stop); process.on('SIGTERM', stop);
