const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const t01VoiceService = require('./t01VoiceService');
const ROOT = __dirname;
const PORT = Number(process.env.PORT || 4170);
const HOST = process.env.HOST || '0.0.0.0';
const children = [];
const log = (event, data = {}) => console.log(`[MASTER] ${new Date().toISOString()} ${event}`, JSON.stringify(data));
function loadDotEnv() { const file = path.join(ROOT, '.env'); if (!fs.existsSync(file)) return; for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, ''); } }
loadDotEnv();
function child(label, command, args, cwd, env = {}) { log('SERVICE_START', { service: label, command, args }); const childProcess = spawn(command, args, { cwd: path.join(ROOT, cwd), env: { ...process.env, ...env }, stdio: 'inherit' }); childProcess.on('error', (error) => log('SERVICE_START_FAILED', { service: label, error: error.message })); childProcess.on('exit', (code, signal) => { if (code !== 0) log('SERVICE_EXITED', { service: label, code, signal }); }); children.push(childProcess); }
child('T02', process.execPath, ['server.js'], 'tasks/T02', { PORT: '8081' });
child('T08', process.execPath, ['server.js'], 'tasks/T08', { PORT: '8082' });
child('T03', process.env.SEL_PYTHON || (process.platform === 'win32' ? 'python' : 'python3'), ['-m', 'uvicorn', 'backend.app.main:app', '--host', '127.0.0.1', '--port', '8000'], 'tasks/T03', { SEL_ASSET_PREFIX: '/tasks/T03/frontend/dist/assets/tasks/T03' });
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.png': 'image/png', '.jpg': 'image/jpeg', '.mp3': 'audio/mpeg', '.mp4': 'video/mp4', '.webm': 'audio/webm', '.svg': 'image/svg+xml' };
function proxyRequest(req,res,port,prefix){const targetPath=req.url.startsWith(prefix)?req.url.slice(prefix.length)||'/':req.url;const proxy=http.request({hostname:'127.0.0.1',port,path:targetPath,method:req.method,headers:{...req.headers,host:`127.0.0.1:${port}`}},upstream=>{res.writeHead(upstream.statusCode||502,upstream.headers);upstream.pipe(res)});proxy.on('error',error=>{log('SUBSERVICE_PROXY_FAILED',{port,error:error.message});if(!res.headersSent)res.writeHead(502);res.end('Subservice unavailable')});req.pipe(proxy)}
const server = http.createServer((req, res) => { const url = decodeURIComponent((req.url || '/').split('?')[0]); if (url === '/health') { res.writeHead(200, { 'Content-Type': 'application/json' }); return res.end(JSON.stringify({ status: 'ok', service: 'MASTER' })); } if (url.startsWith('/task/T02/')) return proxyRequest(req,res,8081,'/task/T02'); if (url.startsWith('/task/T08/')) return proxyRequest(req,res,8082,'/task/T08'); if ((url === '/api/t01/voice-score' || url === '/api/t01/text-score') && req.method === 'POST') return t01VoiceService.score(req, res); if (url.startsWith('/api/v1/')) { const proxy = http.request({ hostname: '127.0.0.1', port: 8000, path: req.url, method: req.method, headers: { ...req.headers, host: '127.0.0.1:8000' } }, (upstream) => { res.writeHead(upstream.statusCode || 502, upstream.headers); upstream.pipe(res); }); proxy.on('error', (error) => { log('T03_API_PROXY_FAILED', { error: error.message }); if (!res.headersSent) res.writeHead(502); res.end('T03 API unavailable'); }); req.pipe(proxy); return; } let fileUrl = url === '/' ? '/index.html' : url; let file; if (fileUrl.startsWith('/assets/T07/')) file = path.join(ROOT, 'tasks/T07/dist/assets/T07', fileUrl.slice('/assets/T07/'.length)); else if (fileUrl.startsWith('/assets/index-')) file = path.join(ROOT, 'tasks/T07/dist/assets', fileUrl.slice('/assets/'.length)); else file = path.resolve(ROOT, `.${fileUrl}`); if (!file.startsWith(path.resolve(ROOT)) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { log('PAGE_LOAD_FAILED', { url: fileUrl, status: 404 }); res.writeHead(404); return res.end('Not found'); } res.writeHead(200, { 'Content-Type': mime[path.extname(file).toLowerCase()] || 'application/octet-stream', 'Cache-Control': 'no-store' }); fs.createReadStream(file).pipe(res); });
server.listen(PORT, HOST, () => log('MASTER_READY', { port: PORT, host: HOST }));
const stop = () => { children.forEach((childProcess) => childProcess.kill()); server.close(() => process.exit(0)); };
process.on('SIGINT', stop); process.on('SIGTERM', stop);
