import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from './api'
import { useAssessment } from './context'
import { Phase, SelReport, Trial } from './types'

function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen flex items-center justify-center p-6"><section className="w-full max-w-4xl min-h-[560px] rounded-[2rem] bg-white shadow-xl flex flex-col items-center justify-center p-8 text-center">{children}</section></main>}
export function Home(){const nav=useNavigate();const ctx=useAssessment();const [id,setId]=useState('C001');const [age,setAge]=useState(7);const [error,setError]=useState('');const start=async()=>{try{setError('');const task=await api.task('T03');await api.child(id,age);const s=await api.createSession(id);ctx.setTask(task);ctx.setSessionId(s.session_id);nav('/rule')}catch(e){setError((e as Error).message)}};return <Shell><div className="text-7xl mb-8">⭐</div><h1 className="text-4xl font-bold">欢迎参加游戏</h1><p className="text-2xl mt-4">准备好了吗？</p><div className="grid gap-3 mt-8 max-w-sm w-full"><input aria-label="儿童编号" className="border-2 rounded-xl p-3 text-lg" value={id} onChange={e=>setId(e.target.value)} placeholder="儿童编号"/><input aria-label="年龄" type="number" className="border-2 rounded-xl p-3 text-lg" value={age} onChange={e=>setAge(Number(e.target.value))}/></div>{error&&<p className="text-red-600 mt-3">{error}</p>}<button onClick={start} className="mt-8 bg-sky-600 text-white text-2xl font-bold px-16 py-4 rounded-full hover:bg-sky-700">开始</button></Shell>}
export function Rule(){const {task,sessionId}=useAssessment();const nav=useNavigate();if(!task||!sessionId)return <Missing/>;return <Shell><h1 className="text-3xl font-bold mb-6">听一听游戏规则</h1><video className="w-full max-w-3xl rounded-2xl bg-slate-900" controls playsInline autoPlay src={task.assets.rule_video} onEnded={()=>nav('/practice')}/><button className="mt-6 text-sky-700 underline" onClick={()=>nav('/practice')}>素材调试：跳过视频</button></Shell>}
export function Trials({phase}:{phase:Phase}){const {task,sessionId}=useAssessment();const nav=useNavigate();const [index,setIndex]=useState(0);const [active,setActive]=useState(false);const [enabled,setEnabled]=useState(false);const [clicked,setClicked]=useState(false);const [error,setError]=useState('');const startRef=useRef(0);const responseRef=useRef<{actual_response:'click'|'no_click';response_time:string|null;reaction_time_ms:number|null}>({actual_response:'no_click',response_time:null,reaction_time_ms:null});
  useEffect(()=>{if(!task||!sessionId)return;let cancelled=false;const trials=phase==='practice'?task.practice_trials:task.test_trials;const run=async()=>{try{if(phase==='practice'&&index===0)await api.start(sessionId);if(index>=trials.length){if(phase==='practice')nav('/test');else{await api.complete(sessionId);nav('/done')}return}setActive(false);setEnabled(false);setClicked(false);responseRef.current={actual_response:'no_click',response_time:null,reaction_time_ms:null};await wait(task.timing.pre_stimulus_ms);if(cancelled)return;setActive(true);const trial=trials[index];const audio=new Audio(task.assets[`${trial.stimulus}_audio`]);audio.addEventListener('playing',()=>{startRef.current=performance.now();setEnabled(true)},{once:true});try{await audio.play()}catch{startRef.current=performance.now();setEnabled(true)}await wait(task.timing.response_window_ms);if(cancelled)return;setEnabled(false);await api.response(sessionId,{trial_id:trial.trial_id,trial_order:index+1,phase,condition:trial.condition,stimulus:trial.stimulus,stimulus_started_time:new Date(Date.now()-(performance.now()-startRef.current)).toISOString(),...responseRef.current});await wait(task.timing.inter_trial_interval_ms);if(!cancelled)setIndex(i=>i+1)}catch(e){setError((e as Error).message)}};run();return()=>{cancelled=true}},[index,nav,phase,sessionId,task]);
  if(!task||!sessionId)return <Missing/>
  const trials=phase==='practice'?task.practice_trials:task.test_trials
  const trial=trials[index]
  const click=()=>{
    if(!enabled||clicked)return
    setClicked(true)
    const rt=Math.round(performance.now()-startRef.current)
    responseRef.current={actual_response:'click',response_time:new Date().toISOString(),reaction_time_ms:rt}
  }
  const image=task.assets[`${phase}_${active?'active':'idle'}`]
  return <Shell>
    <p className="mb-5 text-lg">{phase==='practice'?'练习':'正式测评'} · {Math.min(index+1,trials.length)} / {trials.length}</p>
    <div className="relative aspect-video w-full max-w-3xl overflow-hidden rounded-3xl bg-sky-100">
      <img src={image} alt="教室中的星星任务画面" className="absolute inset-0 h-full w-full object-cover"/>
      {trial?.distractor_video&&<>
        <video key={trial.trial_id} src={trial.distractor_video} muted autoPlay playsInline className="pointer-events-none absolute inset-0 h-full w-full object-cover"/>
        <img src={task.assets[active?'star_active':'star_idle']} alt="" className="pointer-events-none absolute left-1/2 top-[58%] aspect-square w-[22%] -translate-x-1/2 -translate-y-1/2 object-contain"/>
      </>}
      <button aria-label="点击画面中央的星星" disabled={!enabled||clicked} onClick={click} className="absolute left-1/2 top-[58%] aspect-square w-[22%] -translate-x-1/2 -translate-y-1/2 rounded-[40%] bg-transparent disabled:cursor-default enabled:cursor-pointer active:scale-95"/>
    </div>
    <p className="mt-6 text-xl">请仔细听声音</p>
    {error&&<p className="text-red-600 mt-3">{error}</p>}
  </Shell>
}
export function Done(){const {sessionId}=useAssessment();return <Shell><div className="text-8xl">🌟</div><h1 className="text-4xl font-bold mt-8">任务完成</h1><p className="text-2xl mt-4">谢谢你的参与</p>{sessionId&&<a href={`/report/${sessionId}`} className="mt-12 rounded-full bg-slate-700 px-8 py-3 text-white">教师／研究者查看报告</a>}</Shell>}
export function Report(){const {sessionId=''}=useParams();const [report,setReport]=useState<SelReport|null>(null);const [error,setError]=useState('');useEffect(()=>{api.report(sessionId).then(setReport).catch(e=>setError(e.message))},[sessionId]);if(error)return <Shell><p className="text-red-700">{error}</p></Shell>;if(!report)return <Shell><p>正在生成报告…</p></Shell>;const p=report.task_performance;return <main className="min-h-screen bg-slate-100 p-5 md:p-10"><article className="mx-auto max-w-5xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-gradient-to-r from-sky-700 to-indigo-700 p-8 text-white"><p className="text-sm tracking-[.25em]">SEL ASSESSMENT</p><h1 className="mt-2 text-3xl font-bold">社会情感能力测评报告</h1><p className="mt-3 opacity-90">T03 · 规则抑制任务</p></header><div className="grid gap-7 p-6 md:p-9"><section className="grid grid-cols-2 gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-4"><Info label="儿童编号" value={report.child.child_id}/><Info label="年龄" value={`${report.child.age} 岁`}/><Info label="任务" value={report.assessment.task_id}/><Info label="完成时间" value={new Date(report.assessment.completed_time).toLocaleString('zh-CN')}/></section><section className="grid items-center gap-7 md:grid-cols-2"><div><h2 className="text-2xl font-bold">SEL五维表现</h2><p className="mt-2 text-slate-500">本次仅测评“自我管理”，其他维度不计为0分。</p><Radar dimensions={report.sel_dimensions}/></div><div className="rounded-3xl bg-sky-50 p-7"><p className="text-sky-800">自我管理</p><div className="mt-2 text-6xl font-bold text-sky-700">{p.score}<span className="text-2xl"> 分</span></div><div className="mt-7 grid grid-cols-2 gap-4"><Metric label="Go准确率" value={p.go_accuracy}/><Metric label="No-Go抑制率" value={p.no_go_accuracy}/><ScoreMetric label="安静条件" value={p.quiet_score}/><ScoreMetric label="干扰条件" value={p.distractor_score}/></div></div></section><Card title="过程指标"><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><Info label="Go遗漏" value={`${p.go_omissions??0} 次`}/><Info label="No-Go误点" value={`${p.no_go_false_alarms??0} 次`}/><Info label="平均反应时" value={p.mean_go_reaction_time_ms===null?'无有效数据':`${p.mean_go_reaction_time_ms} ms`}/><Info label="反应时变异" value={p.go_reaction_time_sd_ms===null?'数据不足':`${p.go_reaction_time_sd_ms} ms`}/></div></Card><section className="grid gap-5 md:grid-cols-2"><Card title="表现解释"><p className="leading-8 text-slate-700">{report.interpretation}</p></Card><Card title="教育支持建议"><ul className="list-disc space-y-3 pl-5 text-left leading-7 text-slate-700">{report.support_suggestions.map(x=><li key={x}>{x}</li>)}</ul></Card></section><p className="border-t pt-5 text-sm text-slate-500">{report.disclaimer}</p></div></article></main>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{Math.round(value*100)}%</p></div>}
function ScoreMetric({label,value}:{label:string;value:number|null}){return <div className="rounded-2xl bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value===null?'—':`${value}分`}</p></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 p-6"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</section>}
function Radar({dimensions}:{dimensions:SelReport['sel_dimensions']}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const dpr=window.devicePixelRatio||1;const size=320;canvas.width=size*dpr;canvas.height=size*dpr;canvas.style.width=`${size}px`;canvas.style.height=`${size}px`;const c=canvas.getContext('2d');if(!c)return;c.scale(dpr,dpr);const labels=['自我觉察','自我管理','社会觉察','人际关系','负责任决策'];const values=[dimensions.self_awareness,dimensions.self_management,dimensions.social_awareness,dimensions.relationship,dimensions.responsible_decision];const center=size/2,r=105,point=(i:number,ratio:number)=>{const a=-Math.PI/2+i*Math.PI*2/5;return [center+Math.cos(a)*r*ratio,center+Math.sin(a)*r*ratio] as const};c.font='14px Microsoft YaHei';c.textAlign='center';c.textBaseline='middle';for(let level=1;level<=5;level++){c.beginPath();for(let i=0;i<5;i++){const [x,y]=point(i,level/5);i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.strokeStyle='#cbd5e1';c.stroke()}for(let i=0;i<5;i++){const [x,y]=point(i,1);c.beginPath();c.moveTo(center,center);c.lineTo(x,y);c.strokeStyle='#dbeafe';c.stroke();const [lx,ly]=point(i,1.25);c.fillStyle=values[i]===null?'#94a3b8':'#334155';c.fillText(labels[i],lx,ly);if(values[i]===null)c.fillText('未测评',lx,ly+18)}const plotted=values.map(v=>v===null?null:v/100);const measured=plotted.map((v,i)=>v===null?null:{i,v});if(measured.some(Boolean)){c.beginPath();measured.forEach(item=>{if(!item)return;const [x,y]=point(item.i,item.v);c.moveTo(center,center);c.lineTo(x,y)});c.strokeStyle='#0284c7';c.lineWidth=5;c.stroke();measured.forEach(item=>{if(!item)return;const [x,y]=point(item.i,item.v);c.beginPath();c.arc(x,y,6,0,Math.PI*2);c.fillStyle='#0284c7';c.fill()})}},[dimensions]);return <canvas ref={ref} className="mx-auto mt-4 max-w-full" role="img" aria-label={`SEL五维雷达图，自我管理${dimensions.self_management}分，其他维度未测评`}/>}
function Missing(){return <Shell><p>测评信息已丢失，请返回首页重新开始。</p><a href="/" className="mt-4 text-sky-700 underline">返回首页</a></Shell>}
function wait(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
