const $=s=>document.querySelector(s);
const RESPONSE_MS=8000;
const PREMATURE_SUBMIT_THRESHOLD=3;
const sessionId=`T08-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const baseRecord={session_id:sessionId,participant_id:'',task_id:'T08'};
const steps={
  P0:{kind:'instruction',video:'T08-P0.mp4',audio:'T08-P0_20260803_22310108.mp3',next:'PRACTICE'},
  PRACTICE:{kind:'practice',video:'T08-P1.mp4',audio:'T08-P1_20260803_22310054.mp3',frame:'T08-P1.png',options:['苹果','香蕉','橙子','其他','不知道'],next:'A1'},
  A1:{kind:'formal',condition:'A',turn_id:'A1',video:'T08-A-0102.mp4',audio:'T08-A-0102_20260803_22310285.mp3',frame:'T08-A-02.png',options:['小狗','小猫','小兔','其他','不知道'],next:'A2'},
  A2:{kind:'formal',condition:'A',turn_id:'A2',video:'T08-A-0304.mp4',audio:'T08-A-0304_20260803_22310242.mp3',frame:'T08-A-04.png',options:['家里','公园','动物园','书/电视','其他','不知道'],next:'B1'},
  B1:{kind:'formal',condition:'B',turn_id:'B1',video:'T08-B-0102.mp4',audio:'T08-B-0102.mp3',frame:'T08-B-02.png',options:['画画','搭积木','看书','玩球','其他','不知道'],next:'B2'},
  B2:{kind:'formal',condition:'B',turn_id:'B2',video:'T08-B-0304.mp4',audio:'T08-B-0304.mp3',frame:'T08-B-04.png',options:['自己','和一个小伙伴','和大家','都可以','不想做','不知道'],next:'END'},
  END:{kind:'end',video:'T08-END.mp4',audio:'T08-END_20260803_22355423.mp3'}
};
let current='P0',phase='idle',selectedIndex=null,responseTimer=null,mediaStart=0,turnMarkerOnset=0,responseOnset=null;
let promptLevel='P0',replayCount=0,prematureTouchCount=0,prematureSubmitAttemptCount=0;
let recorder=null,pendingVoiceBlob=null,currentRecord=null;
const records=[];
let archivedRecords=[];
const session={...baseRecord,communication_access_valid:null,T08_A_score:null,T08_B_score:null,T08_total_score:null,T08_score_locked:false,nextTask:'T01-B'};
const reviewClient=new SELVoice.ReviewClient();

function stopAllMedia(){clearTimeout(responseTimer);$('#video').pause();$('#audio').pause();$('#video').onended=null;$('#audio').onended=null;}
function playSingle(type,src,onEnd){stopAllMedia();const el=$(type==='video'?'#video':'#audio');const other=$(type==='video'?'#audio':'#video');other.pause();el.src=`assets/${src}`;el.currentTime=0;mediaStart=Date.now();if(type==='video'){$('#video').classList.add('active');$('#frame').classList.add('hidden')}else{$('#video').classList.remove('active');$('#frame').classList.remove('hidden')}el.onended=()=>{el.onended=null;onEnd?.()};el.onerror=()=>{el.onerror=null;if(type==='video'&&steps[current].audio)playSingle('audio',steps[current].audio,onEnd);else onEnd?.()};el.play().catch(()=>{if(type==='video'&&steps[current].audio)playSingle('audio',steps[current].audio,onEnd);else onEnd?.()})}
function createHotspots(step,preview=false){const box=$('#hotspots');box.innerHTML='';box.style.setProperty('--count',step.options.length);step.options.forEach((label,i)=>{const b=document.createElement('button');b.className=`hotspot${preview?' premature':''}`;b.type='button';b.setAttribute('aria-label',label);b.onclick=()=>handleCardTouch(i,preview);box.appendChild(b)});box.classList.toggle('active',!!step.frame)}
function alignHotspots(){const image=$('#frame'),canvas=$('#mediaCanvas'),box=$('#hotspots');if(!image.naturalWidth||!image.naturalHeight)return;const cw=canvas.clientWidth,ch=canvas.clientHeight,scale=Math.min(cw/image.naturalWidth,ch/image.naturalHeight),rw=image.naturalWidth*scale,rh=image.naturalHeight*scale,ox=(cw-rw)/2,oy=(ch-rh)/2;box.style.left=`${ox+rw*.024}px`;box.style.top=`${oy+rh*.675}px`;box.style.width=`${rw*.952}px`;box.style.height=`${rh*.31}px`}
function handleCardTouch(index,preview){if(preview||phase!=='response'){prematureTouchCount++;if(phase==='partner')prematureSubmitAttemptCount++;refreshPanel();return}selectedIndex=index;[...document.querySelectorAll('.hotspot')].forEach((b,i)=>b.classList.toggle('selected',i===index));responseOnset??=Date.now();submitPicture()}
function showFrame(step,preview=false){$('#frame').onload=alignHotspots;$('#frame').src=`assets/${step.frame}`;$('#frame').classList.remove('hidden');$('#video').classList.remove('active');createHotspots(step,preview);alignHotspots()}
function setResponseEnabled(enabled){$('#responseControls').classList.toggle('active',enabled);$('#speak').disabled=!enabled;$('#pictureAnswer').disabled=!enabled||selectedIndex===null;$('#turnCue').classList.toggle('active',enabled)}
function beginStep(id){stopAllMedia();current=id;phase='partner';selectedIndex=null;pendingVoiceBlob=null;promptLevel='P0';replayCount=0;prematureTouchCount=0;prematureSubmitAttemptCount=0;responseOnset=null;document.body.classList.remove('support-p2');$('#recordingState').classList.remove('visible');const step=steps[id];setResponseEnabled(false);$('#hotspots').classList.remove('active');if(step.kind==='end'){playSingle('video',step.video,finishTask);return}if(step.frame)showFrame(step,true);playSingle('video',step.video,()=>{if(step.kind==='instruction')beginStep(step.next);else openResponseWindow()});refreshPanel()}
function openResponseWindow(){const step=steps[current];phase='response';showFrame(step,false);turnMarkerOnset=Date.now();setResponseEnabled(true);responseTimer=setTimeout(handleTimeout,RESPONSE_MS);refreshPanel()}
function handleTimeout(){if(phase!=='response')return;if(promptLevel==='P0'){promptLevel='P1';replayCount++;phase='partner';setResponseEnabled(false);showFrame(steps[current],true);playSingle('audio',steps[current].audio,openResponseWindow)}else if(promptLevel==='P1'){promptLevel='P2';document.body.classList.add('support-p2');openResponseWindow()}else{setResponseEnabled(false);if(steps[current].kind==='practice')markCurrentInv('communication_access_not_confirmed');else completeNoResponse()}}
function makeRecord(channel){const step=steps[current];const submit=Date.now();return{...baseRecord,condition:step.condition||'practice',turn_id:step.turn_id||'PRACTICE',communication_access_valid:session.communication_access_valid,partner_audio_start:mediaStart,partner_audio_end:turnMarkerOnset,turn_marker_onset:turnMarkerOnset,prompt_level:promptLevel,replay_count:replayCount,premature_touch_count:prematureTouchCount,premature_submit_attempt_count:prematureSubmitAttemptCount,repeated_premature_submit:prematureSubmitAttemptCount>=PREMATURE_SUBMIT_THRESHOLD,response_channel:channel,selected_option:selectedIndex===null?'':step.options[selectedIndex],raw_audio_file:'',transcript:'',response_onset:responseOnset,submit_time:submit,RT:responseOnset?responseOnset-turnMarkerOnset:null,turn_recognition_score:null,relevance_score:null,turn_score:null,valid_status:'valid',invalid_reason:''}}
function computeTurnRecognition(record){return record.prompt_level==='P0'&&!record.repeated_premature_submit?1:0}
function scoreRecord(record,relevance){record.turn_recognition_score=computeTurnRecognition(record);record.relevance_score=relevance;record.turn_score=record.turn_recognition_score+record.relevance_score}
function submitPicture(){if(phase!=='response'||selectedIndex===null)return;clearTimeout(responseTimer);phase='submitting_picture';setResponseEnabled(false);$('#hotspots').classList.remove('active');const record=makeRecord('picture');scoreRecord(record,1);finalizeRecord(record)}
async function toggleRecording(){
  if(recorder?.recording){await stopVoiceRecording();return}
  if(phase!=='response')return;
  if(!navigator.mediaDevices?.getUserMedia){returnToResponseForVoiceRetry('当前浏览器无法使用麦克风，请检查权限或改用图片回答');return}
  try{
    clearTimeout(responseTimer);phase='recording_starting';$('#pictureAnswer').disabled=true;recorder=new SELVoice.Recorder({language:'zh-CN'});responseOnset??=Date.now();
    await recorder.start();$('#speak').classList.add('recording');$('#speak').textContent='结束录音';
    phase='recording';$('#recordingState').textContent='正在录音，请说完后点击“结束录音”';$('#recordingState').classList.add('visible');refreshPanel();
  }catch(error){returnToResponseForVoiceRetry(`录音未启动，请检查麦克风权限后重试（${error.message||error}）`)}
}
async function stopVoiceRecording(){
  phase='voice_processing';setResponseEnabled(false);clearTimeout(responseTimer);
  let captured;
  try{captured=await recorder.stop()}catch(error){returnToResponseForVoiceRetry(`录音保存失败，请重新录音（${error.message||error}）`);return}
  pendingVoiceBlob=captured.blob;$('#speak').classList.remove('recording');$('#speak').textContent='说一句';
  let localSaved=true;try{await saveAudioBlob(current,pendingVoiceBlob)}catch{localSaved=false}
  if(!captured.audio_captured||!localSaved){returnToResponseForVoiceRetry(!localSaved?'录音保存失败，请重新录音':'录音时间太短或没有收到声音，请重新录音');return}
  $('#recordingState').textContent=`录音已保存（${(captured.duration_ms/1000).toFixed(1)}秒）`;
  const record=makeRecord('voice');
  record.raw_audio_file=`indexeddb://${sessionId}/${steps[current].turn_id||'PRACTICE'}`;record.raw_audio_bytes=pendingVoiceBlob.size;record.audio_duration_ms=captured.duration_ms;record.audio_start_time=captured.audio_start_time;record.audio_end_time=captured.audio_end_time;record.browser_transcript=captured.transcript||'';
  record.turn_recognition_score=computeTurnRecognition(record);
  if(steps[current].kind==='practice'){scoreRecord(record,1);finalizeRecord(record);return}
  try{
    const result=await SELVoice.requestScore('api/voice/score-audio',{participant_id:baseRecord.participant_id,session_id:sessionId,task_id:'T08',condition:record.condition,turn_id:record.turn_id,question:T08VoicePolicy.TURNS[record.turn_id].question,audio_start_time:captured.audio_start_time,audio_end_time:captured.audio_end_time,audio_duration:captured.duration_ms,prompt_level:record.prompt_level,turn_recognition_score:record.turn_recognition_score},pendingVoiceBlob);
    applyAiResult(record,result);
  }catch(error){record.api_error=String(error.message||error);record.valid_status='MANUAL_REVIEW';record.review_status='manual_review';records.push(record);calculateScores();refreshPanel();setTimeout(()=>beginStep(steps[current].next),1200)}
}
function returnToResponseForVoiceRetry(message){clearTimeout(responseTimer);try{recorder?.stream?.getTracks().forEach(track=>track.stop())}catch{}recorder=null;phase='response';pendingVoiceBlob=null;$('#speak').classList.remove('recording');$('#speak').textContent='说一句';$('#recordingState').textContent=message;$('#recordingState').classList.add('visible');setResponseEnabled(true);responseTimer=setTimeout(handleTimeout,RESPONSE_MS);refreshPanel()}
function applyAiResult(record,result){record.server_record_id=result.id||'';record.audio_file_path=result.audio_file_path||'';record.transcript=result.transcript||'';record.semantic_summary=result.semantic_summary||result.model_understanding_text||'';record.category=result.category||'uncertain_audio';record.need_followup=Boolean(result.need_followup);record.confidence=Number(result.confidence)||0;record.reason=result.reason||'';record.review_status=result.review_status||'manual_review';if(record.review_status==='manual_review'||![0,1].includes(result.relevance_score)){record.valid_status='MANUAL_REVIEW';record.relevance_score=null;record.turn_score=null}else{record.valid_status='valid';record.relevance_score=result.relevance_score;record.turn_score=T08VoicePolicy.computeTurnScore(record.turn_recognition_score,record.relevance_score)}records.push(record);calculateScores();refreshPanel();setTimeout(()=>beginStep(steps[current].next),1200)}
function queueVoiceManualReview(reason,extra={}){clearTimeout(responseTimer);$('#speak').classList.remove('recording');$('#speak').textContent='说一句';$('#recordingState').textContent='本次语音需要人工复核';$('#recordingState').classList.add('visible');if(steps[current].kind==='practice'){markCurrentInv(reason);return}const record={...makeRecord('voice'),...extra,valid_status:'MANUAL_REVIEW',review_status:'manual_review',category:'uncertain_audio',reason,relevance_score:null,turn_score:null};record.turn_recognition_score=computeTurnRecognition(record);records.push(record);calculateScores();refreshPanel();setTimeout(()=>beginStep(steps[current].next),1200)}
function saveAudioBlob(turnId,blob){return new Promise((resolve,reject)=>{const req=indexedDB.open('T08RawAudio',1);req.onupgradeneeded=()=>req.result.createObjectStore('audio');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction('audio','readwrite');tx.objectStore('audio').put(blob,`${sessionId}:${steps[turnId].turn_id||'PRACTICE'}`);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}})}
async function codePendingVoice(relevance){const record=records.find(r=>r.valid_status==='MANUAL_REVIEW'&&r.response_channel==='voice');if(!record)return;record.manual_final_score=relevance;record.manual_final_category=relevance===1?'relevant_response':'irrelevant_response';record.valid_status='valid';record.review_status='human_scored';record.relevance_score=relevance;record.turn_score=T08VoicePolicy.computeTurnScore(record.turn_recognition_score,relevance);if(record.server_record_id){try{await reviewClient.save(record.server_record_id,{human_score:relevance,human_category:record.manual_final_category,human_note:'T08 researcher final coding'})}catch(error){record.manual_review_save_error=String(error.message||error)}}calculateScores();refreshPanel()}
function finalizeRecord(record){clearTimeout(responseTimer);if(steps[current].kind==='practice'){session.communication_access_valid=1;record.communication_access_valid=1;records.push(record);setTimeout(()=>beginStep(steps[current].next),1200);return}record.communication_access_valid=session.communication_access_valid;records.push(record);calculateScores();setTimeout(()=>beginStep(steps[current].next),1200);refreshPanel()}
function completeNoResponse(){const record=makeRecord('none');record.turn_recognition_score=0;record.relevance_score=0;record.turn_score=0;finalizeRecord(record)}
function resolveNoResponse(){if(phase!=='awaiting_researcher')return;if(steps[current].kind==='practice')markCurrentInv('communication_access_not_confirmed');else completeNoResponse()}
function markCurrentInv(reason){clearTimeout(responseTimer);const record=currentRecord||makeRecord('none');record.valid_status='INV';record.invalid_reason=reason;record.turn_recognition_score=null;record.relevance_score=null;record.turn_score=null;if(steps[current].kind==='practice'){session.communication_access_valid=0;records.push(record);phase='stopped';setResponseEnabled(false)}else finalizeRecord(record);currentRecord=null;refreshPanel()}
function calculateScores(){const mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;const conditionScore=c=>{const rs=records.filter(r=>r.condition===c);if(rs.length!==2||rs.some(r=>r.valid_status==='INV'||typeof r.turn_score!=='number'))return null;return mean(rs.map(r=>r.turn_score))};session.T08_A_score=conditionScore('A');session.T08_B_score=conditionScore('B');session.T08_total_score=session.T08_A_score===null||session.T08_B_score===null?null:mean([session.T08_A_score,session.T08_B_score])}
function finishTask(){calculateScores();session.T08_score_locked=true;phase='complete';setResponseEnabled(false);$('#hotspots').classList.remove('active');refreshPanel();const result={...session,records,nextTask:'T01-B'};window.dispatchEvent(new CustomEvent('t08complete',{detail:result}));window.parent.postMessage({source:'sel-task',type:'TASK_COMPLETE',taskId:'T08',result},'*')}
function applyManualPrompt(level){if(!['P2','P3'].includes(level)||!['response','awaiting_voice_code'].includes(phase))return;promptLevel=level;document.body.classList.toggle('support-p2',level==='P2');if(level==='P2'&&phase==='response')openResponseWindow();refreshPanel()}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
function scoreText(value,max=2){return typeof value==='number'?`${value} / ${max}`:'待复核'}
function categoryText(value){return({relevant_response:'相关回应',irrelevant_response:'无关回应',uncertain_audio:'无法判断，需人工复核'}[value]||value||'—')}
function reviewStatusText(record){if(record.review_status==='manual_review'||record.valid_status==='MANUAL_REVIEW')return'待人工复核';if(record.review_status==='human_scored')return'人工复核完成';if(record.review_status==='ai_scored')return'AI评分完成';if(record.response_channel==='picture')return'图片回答';return record.valid_status||'—'}
function renderReviewCard(record,index,source){const turn=record.turn_id||'—',question=T08VoicePolicy.TURNS[turn]?.question||'练习/非正式话轮',pending=record.review_status==='manual_review'||record.valid_status==='MANUAL_REVIEW',audio=record.audio_file_path?`<audio controls preload="metadata" src="/${escapeHtml(record.audio_file_path)}"></audio>`:'<p>本条记录没有服务器端录音。</p>';return `<article class="reviewCard${pending?' needsReview':''}" data-record-index="${index}" data-record-source="${source}"><div class="reviewTitle"><h3>${escapeHtml(turn)} · ${escapeHtml(question)}</h3><span class="statusBadge${pending?' pending':''}">${reviewStatusText(record)}</span></div><div class="reviewGrid"><div class="reviewField"><strong>回答方式</strong><span>${record.response_channel==='picture'?'图片':'语音'}</span></div><div class="reviewField"><strong>提示等级 / 录音时长</strong><span>${escapeHtml(record.prompt_level||'—')} / ${record.audio_duration_ms?`${(record.audio_duration_ms/1000).toFixed(1)}秒`:record.audio_duration?`${(record.audio_duration/1000).toFixed(1)}秒`:'—'}</span></div><div class="reviewField"><strong>模型转写</strong><span>${escapeHtml(record.transcript||'—')}</span></div><div class="reviewField"><strong>语义理解</strong><span>${escapeHtml(record.semantic_summary||'—')}</span></div><div class="reviewField"><strong>AI相关性分类</strong><span>${escapeHtml(categoryText(record.category))}</span></div><div class="reviewField"><strong>置信度 / API状态</strong><span>${record.confidence==null?'—':escapeHtml(record.confidence)} / ${record.api_success===true?'成功':record.api_success===false?'未成功':'—'}</span></div><div class="reviewField"><strong>AI理由</strong><span>${escapeHtml(record.reason||'—')}</span></div><div class="reviewField"><strong>人工最终结果</strong><span>${record.manual_final_score==null?'未填写':record.manual_final_score===1?'相关（1分）':'无关（0分）'}</span></div></div><div class="scoreLine"><div class="scoreBox"><strong>轮次识别</strong><span>${scoreText(record.turn_recognition_score,1)}</span></div><div class="scoreBox"><strong>相关回应</strong><span>${scoreText(record.relevance_score,1)}</span></div><div class="scoreBox"><strong>话轮总分</strong><span>${scoreText(record.turn_score,2)}</span></div></div>${audio}<div class="reviewForm"><label>人工相关性评分</label><select data-human-score><option value="">未填写</option><option value="1" ${record.manual_final_score===1?'selected':''}>相关（1分）</option><option value="0" ${record.manual_final_score===0?'selected':''}>无关（0分）</option></select><label>人工备注</label><textarea data-human-note>${escapeHtml(record.manual_note||'')}</textarea><span class="saveStatus" aria-live="polite"></span><button type="button" data-save-review>保存人工复核</button></div></article>`}
function panelScores(formal){const mean=values=>values.length===2&&!values.some(value=>typeof value!=='number')?values.reduce((a,b)=>a+b,0)/2:null,a=mean(formal.filter(r=>r.condition==='A').map(r=>r.turn_score)),b=mean(formal.filter(r=>r.condition==='B').map(r=>r.turn_score));return{a,b,total:typeof a==='number'&&typeof b==='number'?(a+b)/2:null}}
function turnRecognitionBasis(record){const early=Number(record.premature_submit_attempt_count||0);if(record.response_channel==='none')return'无回应';if(record.repeated_premature_submit)return`反复提前点击（${early}次）`;if(record.prompt_level!=='P0')return`${record.prompt_level}提示后回应${early?`；提前${early}次`:''}`;return early?`P0内回应；提前${early}次（未达反复标准）`:'P0内独立回应'}
function renderConversationOverview(formal){if(!formal.length)return'<h3>四话轮对话总览</h3><p>暂无正式话轮记录。</p>';const order=['A1','A2','B1','B2'],byTurn=Object.fromEntries(formal.map(record=>[record.turn_id,record]));return `<h3>四话轮对话总览</h3><div class="overviewWrap"><table class="overviewTable"><thead><tr><th>话轮</th><th>伙伴问题</th><th>儿童回答／模型转写</th><th>轮次判定依据</th><th>AI相关性</th><th>轮次识别</th><th>话轮总分</th></tr></thead><tbody>${order.map(turn=>{const record=byTurn[turn];if(!record)return`<tr><td class="turnCell">${turn}</td><td>${escapeHtml(T08VoicePolicy.TURNS[turn].question)}</td><td>尚无记录</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`;const pending=record.review_status==='manual_review'||record.valid_status==='MANUAL_REVIEW';return`<tr><td class="turnCell">${turn}</td><td>${escapeHtml(T08VoicePolicy.TURNS[turn].question)}</td><td>${escapeHtml(record.transcript||record.selected_option||'未识别')}</td><td>${escapeHtml(turnRecognitionBasis(record))}</td><td class="${pending?'overviewPending':''}">${pending?'待人工复核':escapeHtml(categoryText(record.category))}（${typeof record.relevance_score==='number'?record.relevance_score:'—'}/1）</td><td class="scoreCell">${typeof record.turn_recognition_score==='number'?record.turn_recognition_score:'—'} / 1</td><td class="scoreCell">${typeof record.turn_score==='number'?record.turn_score:'—'} / 2</td></tr>`}).join('')}</tbody></table></div>`}
function refreshPanel(){calculateScores();const currentFormal=records.filter(r=>['A1','A2','B1','B2'].includes(r.turn_id)),formal=currentFormal.length?currentFormal:archivedRecords,source=currentFormal.length?'current':'archive',scores=panelScores(formal),pending=formal.filter(r=>r.review_status==='manual_review'||r.valid_status==='MANUAL_REVIEW').length,shownSession=formal[0]?.session_id||sessionId;$('#panelStatus').textContent=`当前阶段：${current} / ${phase}；当前提示等级：${promptLevel}；显示会话：${shownSession}`;$('#scoreSummary').innerHTML=`<div class="scoreTile"><strong>A条件均分</strong><span>${scoreText(scores.a)}</span></div><div class="scoreTile"><strong>B条件均分</strong><span>${scoreText(scores.b)}</span></div><div class="scoreTile"><strong>T08总分</strong><span>${scoreText(scores.total)}</span></div><div class="scoreTile"><strong>待人工复核</strong><span>${pending} 条</span></div>`;$('#conversationOverview').innerHTML=renderConversationOverview(formal);$('#reviewList').innerHTML=formal.length?formal.map((record,index)=>renderReviewCard(record,source==='current'?records.indexOf(record):index,source)).join(''):'<article class="reviewCard">暂无正式话轮记录。</article>';$('#log').textContent=JSON.stringify({session,records,pending:currentRecord},null,2)}
async function loadReviewRecords(){try{const all=await reviewClient.list('T08');if(!all.length){archivedRecords=[];refreshPanel();return}const latest=all.reduce((value,item)=>String(item.created_at)>String(value.created_at)?item:value,all[0]),latestSession=latest.session_id;archivedRecords=all.filter(item=>item.session_id===latestSession).sort((a,b)=>['A1','A2','B1','B2'].indexOf(a.turn_id)-['A1','A2','B1','B2'].indexOf(b.turn_id)).map(item=>({...item,server_record_id:item.id,response_channel:'voice',valid_status:item.review_status==='manual_review'?'MANUAL_REVIEW':'valid'}));refreshPanel()}catch(error){$('#panelStatus').textContent=`复核记录加载失败：${error.message||error}`}}
async function saveCardReview(button){const card=button.closest('[data-record-index]'),list=card.dataset.recordSource==='archive'?archivedRecords:records,record=list[Number(card.dataset.recordIndex)],scoreValue=card.querySelector('[data-human-score]').value,note=card.querySelector('[data-human-note]').value,status=card.querySelector('.saveStatus');if(scoreValue===''){status.textContent='请先选择人工相关性评分';return}const score=Number(scoreValue);button.disabled=true;status.textContent='正在保存…';try{if(record.server_record_id)await reviewClient.save(record.server_record_id,{human_score:score,human_category:score===1?'relevant_response':'irrelevant_response',human_note:note});record.manual_final_score=score;record.manual_final_category=score===1?'relevant_response':'irrelevant_response';record.manual_note=note;record.relevance_score=score;record.turn_score=T08VoicePolicy.computeTurnScore(record.turn_recognition_score,score);record.review_status='human_scored';record.valid_status='valid';calculateScores();refreshPanel()}catch(error){status.textContent=`保存失败：${error.message||error}`;button.disabled=false}}
function downloadData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({session,records},null,2)],{type:'application/json'}));a.download=`${sessionId}.json`;a.click()}

$('#start').onclick=()=>{$('#start').hidden=true;beginStep('P0')};
$('#pictureAnswer').onclick=submitPicture;
$('#speak').onclick=toggleRecording;
$('#codeRelevant').onclick=()=>codePendingVoice(1);
$('#codeIrrelevant').onclick=()=>codePendingVoice(0);
$('#codeInv').onclick=()=>markCurrentInv('researcher_coded_inv');
$('#applyP2').onclick=()=>applyManualPrompt('P2');
$('#applyP3').onclick=()=>applyManualPrompt('P3');
$('#resolveNoResponse').onclick=resolveNoResponse;
$('#download').onclick=downloadData;
$('#refreshPanel').onclick=loadReviewRecords;
$('#closePanel').onclick=()=>{$('#researcherPanel').hidden=true};
$('#reviewList').onclick=event=>{const button=event.target.closest('[data-save-review]');if(button)saveCardReview(button)};
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='d'){const panel=$('#researcherPanel');panel.hidden=!panel.hidden;if(!panel.hidden)loadReviewRecords()}});
window.addEventListener('resize',alignHotspots);
refreshPanel();
