"use strict";
const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const voiceService=require('./shared/voice-scoring-service');
const policy=require('./shared/t08-voice-policy');
const ROOT=__dirname,DATA_DIR=path.join(ROOT,'data');
function loadEnv(file){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const t=line.trim(),m=t.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);if(!t||t.startsWith('#')||!m||process.env[m[1]]!==undefined)continue;let v=m[2].trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[m[1]]=v}}
loadEnv(path.join(ROOT,'.env'));
const PORT=Number(process.env.PORT||8088),MODEL=process.env.QWEN_OMNI_MODEL||'qwen3.5-omni-flash',BASE_URL=(process.env.DASHSCOPE_BASE_URL||'https://dashscope.aliyuncs.com/compatible-mode/v1').replace(/\/$/,'');
function ensureDataDirs(){const audio=path.join(DATA_DIR,'audio'),records=path.join(DATA_DIR,'records');fs.mkdirSync(audio,{recursive:true});fs.mkdirSync(records,{recursive:true});return{audio,records}}
ensureDataDirs();
const json=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))};
function readJson(req,limit=30*1024*1024){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>limit){reject(new Error('request_too_large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch{reject(new Error('invalid_request_json'))}});req.on('error',reject)})}
const safe=(value,fallback='')=>String(value||fallback).replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80)||fallback;
function extractJson(text){const cleaned=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim(),start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<start)throw new Error('json_not_found');return JSON.parse(cleaned.slice(start,end+1))}
async function callModel(audioBase64,audioFormat,turnId){if(!process.env.DASHSCOPE_API_KEY)throw new Error('DASHSCOPE_API_KEY_not_configured');const turn=policy.TURNS[turnId];if(!turn)throw new Error('unknown_turn');const payload={model:MODEL,messages:[{role:'system',content:policy.buildSystemPrompt(turnId)},{role:'user',content:[{type:'text',text:`当前正式话轮：${turnId}\n当前问题：${turn.question}\n请直接分析儿童原始语音，只返回规定JSON。`},{type:'input_audio',input_audio:{data:`data:audio/${audioFormat};base64,${audioBase64}`,format:audioFormat}}]}],modalities:['text'],temperature:.01};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);try{const response=await fetch(`${BASE_URL}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${process.env.DASHSCOPE_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`dashscope_${response.status}:${body?.error?.message||'request_failed'}`);return policy.normalizeModelResult(extractJson(body?.choices?.[0]?.message?.content))}finally{clearTimeout(timer)}}
async function scoreAudio(req,res){const input=await readJson(req),turnId=safe(input.turn_id);if(!policy.TURNS[turnId])return json(res,400,{error:'invalid_t08_turn'});const original=Buffer.from(String(input.audio_base64||''),'base64'),extension=safe(input.audio_extension,'webm').toLowerCase();let apiSuccess=false,apiError='',result;if(!original.length||Number(input.audio_duration||0)<400){apiError='empty_or_too_short_audio';result=policy.manualReview(apiError)}else{try{result=await callModel(String(input.api_audio_base64||input.audio_base64||''),safe(input.api_audio_format||extension,'wav'),turnId);apiSuccess=result.review_status==='ai_scored'}catch(error){apiError=String(error.message||error);result=policy.manualReview(apiError)}}const recognition=[0,1].includes(Number(input.turn_recognition_score))?Number(input.turn_recognition_score):null;const record={id:crypto.randomUUID(),participant_id:input.participant_id||'',session_id:input.session_id||'',task_id:'T08',condition:input.condition||turnId[0],turn_id:turnId,question:policy.TURNS[turnId].question,audio_start_time:input.audio_start_time||'',audio_end_time:input.audio_end_time||'',audio_duration:Number(input.audio_duration||0),model_name:MODEL,transcript:result.transcript,model_understanding_text:result.semantic_summary,semantic_summary:result.semantic_summary,relevance_score:result.relevance_score,category:result.category,need_followup:result.need_followup,confidence:result.confidence,reason:result.reason,turn_recognition_score:recognition,turn_score:policy.computeTurnScore(recognition,result.relevance_score),prompt_level:String(input.prompt_level||'P0'),manual_final_score:null,manual_final_category:'',manual_note:'',review_status:result.review_status,api_success:apiSuccess,api_error:apiError};json(res,200,voiceService.saveRecord(DATA_DIR,record,original,extension))}
async function saveReview(req,res,id){const patch=await readJson(req,1024*1024),dirs=ensureDataDirs(),file=path.join(dirs.records,`${safe(id)}.json`);if(!fs.existsSync(file))return json(res,404,{error:'record_not_found'});const record=JSON.parse(fs.readFileSync(file,'utf8')),score=Number(patch.human_score);if(![0,1].includes(score))return json(res,400,{error:'human_score_must_be_0_or_1'});record.manual_final_score=score;record.manual_final_category=String(patch.human_category||'');record.manual_note=String(patch.human_note||'');record.review_status='human_scored';record.turn_score=policy.computeTurnScore(record.turn_recognition_score,score);record.human_modified_at=new Date().toISOString();fs.writeFileSync(file,JSON.stringify(record,null,2));json(res,200,record)}
function serve(req,res,file){const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.mp3':'audio/mpeg','.mp4':'video/mp4','.webm':'audio/webm','.wav':'audio/wav'};if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(file).toLowerCase(),stat=fs.statSync(file),headers={'Content-Type':types[ext]||'application/octet-stream','Cache-Control':file.includes(`${path.sep}assets${path.sep}`)?'public, max-age=604800':'no-cache','Accept-Ranges':'bytes'},match=String(req.headers.range||'').match(/^bytes=(\d*)-(\d*)$/);if(match){const start=match[1]?Number(match[1]):0,end=match[2]?Math.min(Number(match[2]),stat.size-1):stat.size-1;if(start>end||start>=stat.size){res.writeHead(416,{'Content-Range':`bytes */${stat.size}`});return res.end()}res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Content-Length':end-start+1});return fs.createReadStream(file,{start,end}).pipe(res)}res.writeHead(200,{...headers,'Content-Length':stat.size});fs.createReadStream(file).pipe(res)}
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='POST'&&url.pathname==='/api/voice/score-audio')return await scoreAudio(req,res);if(req.method==='GET'&&url.pathname==='/api/voice/reviews')return json(res,200,voiceService.listRecords(DATA_DIR,url.searchParams.get('task_id')||''));const review=url.pathname.match(/^\/api\/voice\/reviews\/([a-zA-Z0-9_-]+)$/);if(req.method==='POST'&&review)return await saveReview(req,res,review[1]);const relative=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),file=path.resolve(ROOT,`.${relative}`);if(!file.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}serve(req,res,file)}catch(error){json(res,500,{error:String(error.message||error)})}}).listen(PORT,'127.0.0.1',()=>console.log(`T08: http://127.0.0.1:${PORT}`));
