(function(global){
  "use strict";
  const now=()=>new Date().toISOString();
  const blobBase64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(blob)});
  function wavBlob(samples,sampleRate){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);const put=(offset,value)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i))};put(0,'RIFF');view.setUint32(4,36+samples.length*2,true);put(8,'WAVE');put(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);put(36,'data');view.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++){const s=Math.max(-1,Math.min(1,samples[i]));view.setInt16(44+i*2,s<0?s*32768:s*32767,true)}return new Blob([buffer],{type:'audio/wav'})}
  async function convertToWav(blob,targetRate=16000){const context=new AudioContext(),decoded=await context.decodeAudioData(await blob.arrayBuffer()),length=Math.ceil(decoded.duration*targetRate),mono=new Float32Array(length),ratio=decoded.sampleRate/targetRate;for(let i=0;i<length;i++){const source=Math.min(decoded.length-1,Math.floor(i*ratio));let value=0;for(let c=0;c<decoded.numberOfChannels;c++)value+=decoded.getChannelData(c)[source];mono[i]=value/decoded.numberOfChannels}await context.close();return wavBlob(mono,targetRate)}
  class Recorder{
    constructor({language='zh-CN'}={}){this.language=language;this.mediaRecorder=null;this.stream=null;this.recognition=null;this.chunks=[];this.transcript='';this.startedAt=0;this.startedIso=''}
    get recording(){return this.mediaRecorder?.state==='recording'}
    async start(onTranscript){this.stream=await navigator.mediaDevices.getUserMedia({audio:true});this.chunks=[];this.transcript='';this.startedAt=performance.now();this.startedIso=now();this.mediaRecorder=new MediaRecorder(this.stream);this.mediaRecorder.ondataavailable=event=>this.chunks.push(event.data);const SR=global.SpeechRecognition||global.webkitSpeechRecognition;if(SR){this.recognition=new SR();this.recognition.lang=this.language;this.recognition.onresult=event=>{this.transcript=Array.from(event.results).map(result=>result[0].transcript).join('');onTranscript?.(this.transcript)};try{this.recognition.start()}catch{}}this.mediaRecorder.start();return{audio_start_time:this.startedIso}}
    stop(){return new Promise((resolve,reject)=>{if(!this.recording)return reject(new Error('not_recording'));this.mediaRecorder.onerror=event=>reject(event.error||new Error('recording_failed'));this.mediaRecorder.onstop=()=>{this.stream?.getTracks().forEach(track=>track.stop());try{this.recognition?.stop()}catch{}const audio_end_time=now(),duration_ms=Math.round(performance.now()-this.startedAt),blob=new Blob(this.chunks,{type:this.mediaRecorder.mimeType||'audio/webm'});resolve({blob,transcript:this.transcript,audio_start_time:this.startedIso,audio_end_time,duration_ms,audio_captured:blob.size>800&&duration_ms>=400})};this.mediaRecorder.stop()})}
  }
  async function requestScore(endpoint,payload,blob){const original=await blobBase64(blob);let apiBlob=blob,apiFormat='webm';try{apiBlob=await convertToWav(blob);apiFormat='wav'}catch{}const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,audio_base64:original,audio_extension:'webm',api_audio_base64:await blobBase64(apiBlob),api_audio_format:apiFormat})});if(!response.ok)throw new Error(`server_${response.status}`);return response.json()}
  class ReviewClient{constructor(base='/api/voice/reviews'){this.base=base}async list(taskId){const response=await fetch(`${this.base}?task_id=${encodeURIComponent(taskId)}`,{cache:'no-store'});if(!response.ok)throw new Error(`server_${response.status}`);return response.json()}async save(id,patch){const response=await fetch(`${this.base}/${encodeURIComponent(id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!response.ok)throw new Error(`server_${response.status}`);return response.json()}}
  global.SELVoice=Object.freeze({Recorder,ReviewClient,requestScore,blobBase64,convertToWav});
})(window);
