const stage=document.querySelector('#stage');let voice=null,narrationToken=0;
const A='assets/';let step='intro',started=0,stepAt=0,blueDone=false,yellowDone=false,choice1=null,choice2=null;const log=[];
const result={task_id:'T04',T04_start_time:null,T04_strategy1_choice:null,T04_strategy1_score:null,T04_strategy1_latency:null,T04_strategy1_prompted_continue:0,T04_repair1_completed:0,T04_repair1_support_level:'P0',T04_repair1_latency:null,T04_strategy2_choice:null,T04_strategy2_score:null,T04_strategy2_latency:null,T04_strategy2_prompted_continue:0,T04_final_repair_completed:0,T04_final_repair_support_level:'P0',T04_final_repair_latency:null,T04_total_duration:null,T04_completed:0,T04_score_locked:0};
function setStep(next){step=next;stepAt=performance.now();log.push({event:'step',step:next,time:Date.now()});save();render()}
function save(){localStorage.setItem('T04_task_data',JSON.stringify({...result,event_log:log}))}
function video(file,onEnd,poster=''){stage.innerHTML=`<video id="sceneVideo" ${poster?`poster="${A+poster}"`:''} autoplay playsinline src="${A+file}"></video>`;const v=document.querySelector('#sceneVideo');v.onended=onEnd;v.onerror=()=>onEnd()}
function stopAudio(){narrationToken++;if(voice){voice.pause();voice.currentTime=0;voice=null}}
function audio(file,onEnd,card){stopAudio();const token=narrationToken;voice=new Audio(A+file+'?v=20260810a');voice.playbackRate=card&&card.classList.contains('card')?0.82:1;voice.volume=file.includes('T04_A07_option_')?0.62:1;if(card)card.classList.add('reading');const done=()=>{if(card)card.classList.remove('reading');if(token===narrationToken&&onEnd)onEnd()};voice.onended=done;voice.onerror=done;voice.play().catch(done)}
function drag(el,id){el.draggable=true;el.ondragstart=e=>e.dataTransfer.setData('text/plain',id)}
function drop(el,id,fn){el.ondragover=e=>e.preventDefault();el.ondrop=e=>{if(e.dataTransfer.getData('text/plain')===id)fn()}}
function pointerDrag(el,target,onSuccess,onStart){const original=el.getAttribute('style')||'';el.draggable=false;el.style.touchAction='none';let dx=0,dy=0,moved=false;el.onpointerdown=e=>{e.preventDefault();if(onStart)onStart();const er=el.getBoundingClientRect(),sr=stage.getBoundingClientRect();dx=e.clientX-er.left;dy=e.clientY-er.top;moved=false;el.style.left=((er.left-sr.left)/sr.width*100)+'%';el.style.top=((er.top-sr.top)/sr.height*100)+'%';el.style.right='auto';el.style.bottom='auto';el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!el.hasPointerCapture(e.pointerId))return;moved=true;const sr=stage.getBoundingClientRect();el.style.left=((e.clientX-sr.left-dx)/sr.width*100)+'%';el.style.top=((e.clientY-sr.top-dy)/sr.height*100)+'%'};el.onpointerup=e=>{if(!el.hasPointerCapture(e.pointerId))return;el.releasePointerCapture(e.pointerId);const tr=target.getBoundingClientRect(),er=el.getBoundingClientRect();const overlaps=er.left<tr.right&&er.right>tr.left&&er.top<tr.bottom&&er.bottom>tr.top;if(moved&&overlaps)onSuccess();else el.setAttribute('style',original)};el.onclick=e=>e.preventDefault();el.ondblclick=e=>e.preventDefault()}
function strategyCards(round){const one=round===1;const cards=one?[['rebuild','T04_A03_strategy_rebuild.PNG','T04_A03_option_rebuild.mp3','重新搭好'],['ask_dog','T04_A03_strategy_ask_dog.PNG','T04_A03_option_ask_dog.mp3','请泡泡狗帮忙'],['stop','T04_A03_strategy_stop_building.PNG','T04_A03_option_stop.mp3','不想搭了'],['unknown','T04_A03_strategy_unknown.PNG','T04_A03_option_unknown.mp3','不知道']]:[['check_castle','T04_A07_strategy_check_castle.PNG','T04_A07_option_check_castle.mp3','看看哪里没搭好'],['ask_dog','T04_A07_strategy_ask_dog.PNG','T04_A07_option_ask_dog.mp3','请泡泡狗帮忙'],['stop','T04_A07_strategy_stop.PNG','T04_A07_option_stop.mp3','不想搭了'],['unknown','T04_A07_strategy_unknown.PNG','T04_A07_option_unknown.mp3','不知道']];stage.innerHTML=`<div class="card-screen" style="background-image:url('${A+(one?'T04_A03_strategy_question_end.png':'T04_A06_strategy2_question_end.png')}')"><div class="cards">${cards.map(c=>`<button class="card" data-choice="${c[0]}" data-audio="${c[2]}" disabled><img src="${A+c[1]}" alt="${c[3]}"><span class="card-label">${c[3]}</span></button>`).join('')}</div></div>`;const buttons=[...document.querySelectorAll('.card')];buttons.forEach(b=>{b.onclick=()=>choose(round,b.dataset.choice)});let i=0;const next=()=>{if(i>=buttons.length){buttons.forEach(b=>b.disabled=false);return}const b=buttons[i++];audio(b.dataset.audio,()=>setTimeout(next,850),b)};next()}
function choose(round,choice){const latency=Math.round(performance.now()-stepAt),score=(choice==='rebuild'||choice==='check_castle')?2:choice==='ask_dog'?1:0;if(round===1){choice1=choice;result.T04_strategy1_choice=choice;result.T04_strategy1_score=score;result.T04_strategy1_latency=latency}else{choice2=choice;result.T04_strategy2_choice=choice;result.T04_strategy2_score=score;result.T04_strategy2_latency=latency}log.push({event:'strategy_choice',round,choice,score,latency,time:Date.now()});save();if(choice==='stop'||choice==='unknown'){if(round===1)result.T04_strategy1_prompted_continue=1;else result.T04_strategy2_prompted_continue=1;save();audio('T04_common_continue_prompt.mp3');stage.innerHTML+=`<button id="continuePrompt" class="continue">继续</button>`;document.querySelector('#continuePrompt').onclick=()=>round===1?setStep('repairBlueIntro'):setStep('helpBlock')}else round===1?setStep('repairBlueIntro'):setStep('helpBlock')}
function render(){stopAudio();
if(step==='intro'){stage.innerHTML=`<div class="video-cover"><img src="${A}T04_V00_intro_start.png" alt="任务介绍首帧"><button id="start" class="start">开始</button></div>`;document.querySelector('#start').onclick=()=>{started=performance.now();result.T04_start_time=new Date().toISOString();save();setStep('introVideo')}}
else if(step==='introVideo')video('T04_V00_task_intro.mp4',()=>setStep('flag'));
else if(step==='flag'){stage.innerHTML=`<div class="scene"><img class="scene-img" src="${A}T04_A01_interaction_base.PNG" alt="城堡插旗交互画面"><img id="flag" class="flag" src="${A}T04_red_flag_without_base_transparent.png" alt="红旗"><div id="flagHole" class="flag-hole"></div></div>`;audio('T04_A01_instruction.mp3');const f=document.querySelector('#flag'),h=document.querySelector('#flagHole');pointerDrag(f,h,()=>setStep('drop'))}
else if(step==='drop')video('T04_A02_block_drop.mp4',()=>setStep('question1'),'T04_A02_block_drop_start.png');
else if(step==='question1')video('T04_A03_strategy_question.mp4',()=>setStep('cards1'));
else if(step==='cards1')strategyCards(1);
else if(step==='repairBlueIntro')video('T04_A04_repair_instruction.mp4',()=>setStep('repairBlue'));
else if(step==='repairBlue'){stage.innerHTML=`<div class="scene"><img class="scene-img" src="${A}T04_A04_repair_base.png" alt="A04蓝色积木修复画面"><img id="blue" class="blue-block" src="${A}T04_second_blue_block_transparent.png" alt="蓝色积木"><div id="blueTarget" class="blue-target"></div></div>`;const t0=performance.now(),bg=stage.querySelector('.scene-img'),b=document.querySelector('#blue'),z=document.querySelector('#blueTarget');const done=()=>{if(blueDone)return;blueDone=true;result.T04_repair1_completed=1;result.T04_repair1_latency=Math.round(performance.now()-t0);save();setStep('feedback')};pointerDrag(b,z,done,()=>bg.src=A+'T04_A04_interaction_base.PNG')}
else if(step==='feedback')video('T04_A05_negative_feedback.mp4',()=>setStep('question2'),'T04_A05_negative_feedback_start.PNG');
else if(step==='question2')video('T04_A06_strategy2_question.mp4',()=>setStep('cards2'),'T04_A06_strategy2_question_start.PNG');
else if(step==='cards2')strategyCards(2);
else if(step==='helpBlock')video('T04_A08_help_block.mp4',()=>setStep('finalRepair'),'T04_A08_help_block_start.png');
else if(step==='finalRepair'){stage.innerHTML=`<div class="scene"><img class="scene-img" src="${A}T04_A08_help_block_start.png" alt="A08关键积木交互画面"><img id="yellow" class="yellow-block" src="${A}T04_top_yellow_block_transparent.png" alt="黄色关键积木"><img id="finalFlag" class="final-flag locked" src="${A}T04_red_flag_without_base_transparent.png" alt="红旗"><div id="yellowTarget" class="yellow-target"></div><div id="finalFlagHole" class="final-flag-hole"></div></div>`;audio('T04_A09_final_repair_instruction.mp3');const t0=performance.now(),y=document.querySelector('#yellow'),yt=document.querySelector('#yellowTarget'),f=document.querySelector('#finalFlag'),fh=document.querySelector('#finalFlagHole');const finishRepair=()=>{if(!yellowDone)return;result.T04_final_repair_completed=1;result.T04_final_repair_latency=Math.round(performance.now()-t0);save();setStep('complete')};const placeY=()=>{if(yellowDone)return;yellowDone=true;stage.querySelector('.scene-img').src=A+'T04_A09_interaction_base.PNG';y.style.left='45.1%';y.style.top='40%';y.style.bottom='auto';y.style.width='9.5%';y.style.pointerEvents='none';f.classList.remove('locked');pointerDrag(f,fh,finishRepair);save()};pointerDrag(y,yt,placeY)}
else if(step==='complete')video('T04_A10_complete_feedback.mp4',()=>{result.T04_total_duration=Math.round(performance.now()-started);result.T04_completed=1;result.T04_score_locked=1;localStorage.setItem('T04_score_locked','1');save();window.parent.postMessage({source:'sel-task',type:'TASK_COMPLETE',taskId:'T04',result:{...result,score:[result.T04_strategy1_score,result.T04_strategy2_score].filter(x=>typeof x==='number').reduce((a,b)=>a+b,0)/2}},'*');setStep('done')},'T04_A10_complete_feedback_start.png');
else{const scores=[result.T04_strategy1_score,result.T04_strategy2_score].filter(x=>x!==null);const total=scores.length? scores.reduce((a,b)=>a+b,0)/scores.length:null;stage.innerHTML=`<div class="done"><img src="${A}T04_A10_complete_feedback_end.png" alt="城堡完成"><div class="done-actions"><button id="exportJson">导出JSON</button><button id="restart">重新开始</button></div></div>`;document.querySelector('#exportJson').onclick=()=>download({...result,T04_score:total,event_log:log});document.querySelector('#restart').onclick=()=>location.reload()}}
function download(obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download='T04_result.json';a.click();URL.revokeObjectURL(a.href)}
render();
