(() => {
  "use strict";
  const VERSION="T02-V4.0-2026.08.10",ASSET="assets/",$=id=>document.getElementById(id);
  const ui={setup:$('setup'),stage:$('stage'),result:$('result'),sceneImage:$('sceneImage'),sceneVideo:$('sceneVideo'),overlay:$('overlay'),prompt:$('prompt'),cards:$('cards'),mic:$('micBtn'),next:$('nextBtn'),step:$('stepLabel'),progress:$('progressText'),dock:$('responseDock'),voice:$('voiceEntry'),picture:$('pictureEntry'),voiceStatus:$('voiceStatus'),research:$('researchPanel'),reviewList:$('reviewList')};
  let session=null,timers=[],recorder=null,recordingMeta=null,currentCondition="",sceneStart=0,aState=null,bState=null,aNarrationToken=0,aNarrationAudio=null,aNarrationSource=null,bNarrationToken=0,bNarrationAudio=null;const reviewClient=new SELVoice.ReviewClient();
  const src=n=>ASSET+encodeURIComponent(n),now=()=>new Date().toISOString(),show=e=>e.classList.remove('hidden'),hide=e=>e.classList.add('hidden');
  function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id} function clearTimers(){timers.forEach(clearTimeout);timers=[]}
  function fresh(){return {child_id:$('childId').value.trim()||"anonymous",session_id:crypto.randomUUID(),task_id:"T02",timestamp:now(),version:VERSION,A_complete:false,A_completion_time:null,A_rotate_used:false,A_error_attempt:0,A_hint_level:0,B_complete:false,B_check_material:false,B_identify_missing:false,B_help_request:false,B_help_specificity:0,B_hint_level:0,B_audio_captured:false,B_speech_semantic_clear:false,B_prompt_level:0,A_score:null,B_score:null,T02_A_score:null,T02_B_score:null,T02_total_score:null,speech_records:[],ai_records:[],choices:[],events:[]}}
  function persist(){if(session)localStorage.setItem('T02_last_session',JSON.stringify(session))} function log(type,data={}){session.events.push({timestamp:now(),condition:currentCondition,type,...data});persist()}
  function resetStage(){clearTimers();ui.overlay.innerHTML='';ui.cards.innerHTML='';hide(ui.cards);hide(ui.mic);hide(ui.dock);hide(ui.next);ui.sceneVideo.pause();hide(ui.sceneVideo);show(ui.sceneImage)}
  function scene(img,text,step,progress){resetStage();ui.sceneImage.src=src(img);ui.prompt.textContent=text;ui.step.textContent=step;ui.progress.textContent=progress;sceneStart=performance.now()}
  function audio(name,volume=1){const a=new Audio(src(name));a.volume=volume;a.play().catch(()=>{});return a}
  function stopAChoiceAudio(){aNarrationToken++;if(aNarrationAudio){aNarrationAudio.pause();aNarrationAudio.currentTime=0;aNarrationAudio=null}if(aNarrationSource){try{aNarrationSource.stop()}catch{}aNarrationSource=null}ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'))}
  function stopBChoiceAudio(){bNarrationToken++;if(bNarrationAudio){bNarrationAudio.pause();bNarrationAudio.currentTime=0;bNarrationAudio=null}ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'))}
  function tone(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}
  function preloadImage(name){return new Promise(ok=>{const img=new Image();img.onload=img.onerror=()=>ok();img.src=src(name)})}
  function video(name,end,onEnd){resetStage();show(ui.sceneImage);show(ui.sceneVideo);ui.sceneVideo.classList.remove('ready');ui.sceneVideo.src=src(name);let done=false;const reveal=()=>ui.sceneVideo.classList.add('ready');const finish=async()=>{if(done)return;done=true;await preloadImage(end);ui.sceneImage.onload=()=>{ui.sceneVideo.classList.remove('ready');later(()=>hide(ui.sceneVideo),180)};ui.sceneImage.src=src(end);if(ui.sceneImage.complete)ui.sceneImage.onload();onEnd?.()};ui.sceneVideo.oncanplay=reveal;ui.sceneVideo.onplaying=reveal;ui.sceneVideo.onended=finish;ui.sceneVideo.play().catch(finish)}
  async function database(){return new Promise((ok,no)=>{const r=indexedDB.open('T02_audio',1);r.onupgradeneeded=()=>r.result.createObjectStore('audio',{keyPath:'audio_file'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
  async function storeAudio(row){try{const d=await database(),tx=d.transaction('audio','readwrite');tx.objectStore('audio').put(row);await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});d.close()}catch(e){log('audio_store_error',{message:e.message})}}
  function classify(text){if(currentCondition.startsWith('A')&&/转|方向|角度/.test(text)){session.A_rotate_used=true;log('speech_strategy',{strategy:'rotate'})}}
  function setVoiceLabel(text){const label=ui.voice.querySelector('span');if(label)label.textContent=text}
  function blobBase64(blob){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]||'');r.onerror=no;r.readAsDataURL(blob)})}
  function wavBlob(samples,sampleRate){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);const text=(offset,value)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i))};text(0,'RIFF');view.setUint32(4,36+samples.length*2,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++){const s=Math.max(-1,Math.min(1,samples[i]));view.setInt16(44+i*2,s<0?s*32768:s*32767,true)}return new Blob([buffer],{type:'audio/wav'})}
  async function convertToWav(blob,targetRate=16000){const context=new AudioContext(),decoded=await context.decodeAudioData(await blob.arrayBuffer()),length=Math.ceil(decoded.duration*targetRate),mono=new Float32Array(length),ratio=decoded.sampleRate/targetRate;for(let i=0;i<length;i++){const source=Math.min(decoded.length-1,Math.floor(i*ratio));let value=0;for(let c=0;c<decoded.numberOfChannels;c++)value+=decoded.getChannelData(c)[source];mono[i]=value/decoded.numberOfChannels}await context.close();return wavBlob(mono,targetRate)}
  async function requestAiScore(blob,meta){return SELVoice.requestScore('/api/voice/score-audio',{participant_id:session.child_id,session_id:session.session_id,task_id:'T02',scene_id:'T02_B_MISSING_LEAF',question_id:'T02_B_OPEN_VOICE',question:'发生了什么？你需要什么帮助？',audio_start_time:meta.audio_start_time,audio_end_time:meta.audio_end_time,audio_duration:meta.duration_ms,prompt_level:session.B_prompt_level||0},blob)}
  function handleAiResult(record){session.ai_records.push(record);log('ai_score_received',{record_id:record.id,category:record.ai_category,score:record.ai_score,confidence:record.ai_confidence,next_action:record.next_action,api_success:record.api_success});persist();if(bState?.resolved){log('late_ai_result_ignored',{record_id:record.id});return}const decision=T02VoicePolicy.routeVoice({category:record.ai_category,nextAction:record.next_action,promptLevel:session.B_prompt_level||0,wrongAttempts:bState?.wrongChoiceCount||0,uncertainAttempts:bState?.uncertainAttempts||0});ui.voiceStatus.textContent='我听到了。';ui.prompt.textContent='我听到了。';if(decision.kind==='provide_piece'){session.B_identify_missing=true;session.B_help_request=true;session.B_help_specificity=2;persist();later(provideLeaf,700);return}if(decision.kind==='neutral_followup'){session.B_prompt_level=1;ui.prompt.textContent='你需要泡泡狗帮你拿什么？';ui.voiceStatus.textContent='请再说具体一点。';audio('T02_B02_followup_need_what.mp3');showDock('voice');persist();return}if(decision.kind==='finish_vague'){finishBVagueAfterFollowup();return}if(decision.kind==='retry'){retryOrEndB(decision.reason);persist();return}if(decision.kind==='finish_zero'){finishBUnresolved(decision.reason,{helpRequest:record.ai_category==='request_adult_complete',helpSpecificity:record.ai_category==='request_adult_complete'?1:0});return}if(decision.kind==='manual_finish'){finishBManualReview(record.api_error||'uncertain_audio_after_retry');return}bState.uncertainAttempts++;log('voice_manual_review_retry',{attempt:bState.uncertainAttempts,reason:record.api_error||'uncertain_audio'});ui.voiceStatus.textContent='没有听清楚，请再说一次。';ui.prompt.textContent='没有听清楚，请再说一次，或用图片回答。';showDock('both');persist()}
  async function scoreCapturedBVoice(blob,meta){clearTimeout(bState?.voiceFallbackTimer);clearTimeout(bState?.p1Timer);clearTimeout(bState?.p2Timer);if(bState)bState.aiProcessing=true;ui.voiceStatus.textContent='我听到了。';ui.prompt.textContent='我听到了。';ui.voice.disabled=true;hide(ui.picture);try{const record=await requestAiScore(blob,meta);handleAiResult(record)}catch(e){log('ai_api_error',{message:e.message});ui.prompt.textContent='我听到了。你可以再说一次，或用图片回答。';ui.voiceStatus.textContent='请再说一次。';showDock('both')}finally{if(bState)bState.aiProcessing=false;ui.voice.disabled=false}}
  async function toggleMic(){
    if(recorder?.recording){
      ui.voiceStatus.textContent='我听到了。';setVoiceLabel('说一说');
      try{const captured=await recorder.stop();ui.voice.classList.remove('recording');ui.mic.classList.remove('recording');if(bState)bState.recording=false;const meta=recordingMeta||{},audio_file=meta.audio_file||`T02_B_${Date.now()}.webm`,condition=meta.condition||currentCondition,row={audio_file,speech_text:captured.transcript,timestamp:captured.audio_end_time,condition,task_id:'T02',duration_ms:captured.duration_ms,audioCaptured:captured.audio_captured,blob:captured.blob};await storeAudio(row);session.speech_records.push({audio_file,speech_text:captured.transcript,timestamp:captured.audio_end_time,condition,duration_ms:captured.duration_ms,audio_captured:captured.audio_captured});log('record_saved',{audio_file,speech_text:captured.transcript,duration_ms:captured.duration_ms,audio_captured:captured.audio_captured});if(condition.startsWith('B')&&bState&&!bState.resolved){bState.voiceCollected=captured.audio_captured;session.B_audio_captured=captured.audio_captured;persist();await scoreCapturedBVoice(captured.blob,captured)}}catch(e){log('record_stop_error',{message:e.message});showDock('both')}return
    }
    try{if(bState?.resolved)return;const index=String(session.speech_records.length+1).padStart(3,'0');recordingMeta={audio_file:`T02_${currentCondition.replace(/[^A-Z0-9_]/gi,'_')}_${index}.webm`,condition:currentCondition};recorder=new SELVoice.Recorder({language:'zh-CN'});if(bState){clearTimeout(bState.voiceFallbackTimer);clearTimeout(bState.p1Timer);clearTimeout(bState.p2Timer);bState.recording=true;bState.aiProcessing=false;bState.pictureShown=false;hide(ui.picture);setVoiceLabel('说完了');ui.voiceStatus.textContent='正在听你说……说完后请点“说完了”';ui.prompt.textContent='正在听你说……'}const started=await recorder.start(classify);ui.voice.classList.add('recording');ui.mic.classList.add('recording');log('record_start',started)}catch(e){if(bState)bState.recording=false;setVoiceLabel('说一说');ui.prompt.textContent='麦克风暂不可用，你可以重新尝试或用图片回答。';ui.voiceStatus.textContent='麦克风暂不可用';log('microphone_unavailable',{message:e.message});showDock('both')}
  }
  function pointerDrag(el,home,onRelease){let active=false,pointerId=null,dx=0,dy=0;el.draggable=false;el.setAttribute('draggable','false');el.addEventListener('dragstart',e=>e.preventDefault());el.addEventListener('pointerdown',e=>{if(active)return;e.preventDefault();active=true;pointerId=e.pointerId;const r=el.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top;el.setPointerCapture(pointerId);el.style.transition='none';el.style.cursor='grabbing';log('drag_start')});el.addEventListener('pointermove',e=>{if(!active||e.pointerId!==pointerId)return;const s=ui.stage.getBoundingClientRect();el.style.left=`${e.clientX-s.left-dx}px`;el.style.top=`${e.clientY-s.top-dy}px`;e.preventDefault()});const finish=e=>{if(!active||e.pointerId!==pointerId)return;e.preventDefault();active=false;try{el.releasePointerCapture(pointerId)}catch{}el.style.cursor='grab';onRelease(el,()=>snapBack(el,home))};el.addEventListener('pointerup',finish);el.addEventListener('pointercancel',e=>{if(active){active=false;snapBack(el,home)}})}
  function snapBack(el,home){el.style.transition='left .24s ease,top .24s ease';el.style.left=home.left;el.style.top=home.top;later(()=>el.style.transition='none',260)}
  function hits(el,target){const a=el.getBoundingClientRect(),b=target.getBoundingClientRect(),x=a.left+a.width/2,y=a.top+a.height/2;return x>b.left&&x<b.right&&y>b.top&&y<b.bottom}
  function cards(items,pick){ui.cards.innerHTML='';items.forEach((x,i)=>{const b=document.createElement('button');b.className='card';b.dataset.index=i;b.innerHTML=`<img src="${src(x.img)}" alt=""><span class="card-label">${x.label}</span>`;b.onclick=()=>{session.choices.push({choice_id:x.id,choice_content:x.label,condition:currentCondition,timestamp:now()});log('choice',{choice_id:x.id,choice_content:x.label});pick(x)};ui.cards.appendChild(b)});show(ui.cards)}
  function detectSpeechSegments(buffer,count=4){const data=buffer.getChannelData(0),rate=buffer.sampleRate,windowSize=Math.max(1,Math.floor(rate*.02)),levels=[];let peak=0;for(let start=0;start<data.length;start+=windowSize){let sum=0,n=Math.min(windowSize,data.length-start);for(let i=0;i<n;i++){const value=data[start+i];sum+=value*value}const rms=Math.sqrt(sum/n);levels.push(rms);peak=Math.max(peak,rms)}const threshold=Math.max(.006,peak*.055),maxSilentWindows=Math.ceil(.18/.02),ranges=[];let speechStart=-1,lastActive=-1;for(let i=0;i<levels.length;i++){if(levels[i]>=threshold){if(speechStart<0)speechStart=i;lastActive=i}else if(speechStart>=0&&i-lastActive>maxSilentWindows){if((lastActive-speechStart)*.02>=.22)ranges.push([speechStart*.02,Math.min(buffer.duration,(lastActive+1)*.02)]);speechStart=-1;lastActive=-1}}if(speechStart>=0&&lastActive>=speechStart)ranges.push([speechStart*.02,Math.min(buffer.duration,(lastActive+1)*.02)]);while(ranges.length>count){let gapIndex=0,gap=Infinity;for(let i=0;i<ranges.length-1;i++){const current=ranges[i+1][0]-ranges[i][1];if(current<gap){gap=current;gapIndex=i}}ranges.splice(gapIndex,2,[ranges[gapIndex][0],ranges[gapIndex+1][1]])}if(ranges.length!==count){const cuts=[0,.27,.56,.82,1];return cuts.slice(0,count).map((x,i)=>[buffer.duration*x,buffer.duration*cuts[i+1]])}return ranges.map(([start,end])=>[Math.max(0,start-.04),Math.min(buffer.duration,end+.06)])}
  function playAudioSegment(context,buffer,start,end){return new Promise(ok=>{const source=context.createBufferSource();aNarrationSource=source;source.buffer=buffer;source.connect(context.destination);source.onended=()=>{if(aNarrationSource===source)aNarrationSource=null;ok()};source.start(0,start,Math.max(.1,end-start))})}
  async function narrateCards(questionAudio){const token=++aNarrationToken;aNarrationAudio=questionAudio;if(questionAudio&&!questionAudio.ended)await new Promise(ok=>{questionAudio.addEventListener('ended',ok,{once:true});later(ok,5000)});if(token!==aNarrationToken)return;await new Promise(ok=>later(ok,1200));if(token!==aNarrationToken)return;let context;try{context=new AudioContext();const response=await fetch(src('T02_A04_option.mp3')),buffer=await context.decodeAudioData(await response.arrayBuffer()),segments=detectSpeechSegments(buffer,4);for(let i=0;i<segments.length;i++){if(token!==aNarrationToken)break;ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'));const el=ui.cards.querySelector(`[data-index="${i}"]`);el?.classList.add('speaking');await playAudioSegment(context,buffer,segments[i][0],segments[i][1]);el?.classList.remove('speaking');if(token!==aNarrationToken)break;await new Promise(ok=>later(ok,1400))}}catch(e){log('strategy_audio_error',{message:e.message})}finally{if(context)await context.close().catch(()=>{});aNarrationSource=null;ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'))}}
  function intro(){currentCondition='INTRO';hide(ui.setup);show(ui.stage);ui.step.textContent='T02 开始说明';ui.progress.textContent='1 / 2';ui.prompt.textContent='有的难题可以自己试一试，有的难题需要把缺少的东西告诉我。';video('T02_V00_task_intro.mp4','T02_V00_task_intro_end.png',()=>later(startA,900))}
  function startA(){currentCondition='A_P0';scene('T02_A01_background_clean.png','把最后一块放进小鱼里。','情境 A · 小鱼拼图','1 / 2');audio('T02_A01_instruction.mp3');const piece=document.createElement('img'),target=document.createElement('div'),rotate=document.createElement('button');piece.src=src('T02_A01_fish_piece.png');piece.id='fishPiece';piece.className='drag-piece';piece.dataset.rotation='90';piece.style.cssText='width:12%;left:76%;top:46%;transform:rotate(90deg)';target.id='fishTarget';target.style.cssText='position:absolute;left:39%;top:43%;width:23%;height:29%';rotate.className='rotate-control';rotate.ariaLabel='旋转拼片';rotate.style.cssText='left:91%;top:72%;width:9%;height:15%';rotate.onclick=()=>rotatePiece(piece,false);ui.overlay.append(target,piece,rotate);aState={piece,target,home:{left:'76%',top:'46%'},p1:false,p2:false,completed:false};pointerDrag(piece,aState.home,(el,back)=>{if(aState.completed)return;if(hits(el,target)&&Number(el.dataset.rotation)%360===0){aState.completed=true;clearTimers();el.style.transition='left .18s ease,top .18s ease,transform .18s ease';el.style.left='44%';el.style.top='50%';el.style.pointerEvents='none';log('piece_snapped');later(()=>completeA(),180)}else{session.A_error_attempt++;log('invalid_drop',{rotation:Number(el.dataset.rotation),count:session.A_error_attempt});back()}});later(()=>{if(!session.A_complete&&!aState.completed&&!aState.p1)hintA1()},12000)}
  function rotatePiece(piece,emphasis){session.A_rotate_used=true;piece.dataset.rotation=String((Number(piece.dataset.rotation)+90)%360);piece.style.setProperty('--rotation',`${piece.dataset.rotation}deg`);piece.style.transform=`rotate(${piece.dataset.rotation}deg)`;piece.classList.remove('strategy-rotate');void piece.offsetWidth;if(emphasis){piece.classList.add('strategy-rotate');tone();later(()=>piece.classList.remove('strategy-rotate'),1300)}else tone();log('rotate',{rotation:Number(piece.dataset.rotation),source:emphasis?'strategy_card':'button'})}
  function hintA1(){if(aState.p1||session.A_complete)return;aState.p1=true;currentCondition='A_P1';session.A_hint_level=1;ui.prompt.textContent='再看看怎么放进去。';audio('T02_A03_P1_instruction.mp3');log('hint',{level:1});aState.invalidStreak=0;later(()=>{if(!session.A_complete&&!aState.p2)hintA2()},8000)}
  function hintA2(){if(aState.p2||session.A_complete)return;aState.p2=true;currentCondition='A_P2';session.A_hint_level=2;ui.prompt.textContent='你想先试哪一种办法？';const questionAudio=audio('T02_A04_question.mp3');log('hint',{level:2});cards([{id:'A01',label:'转一转',img:'T02_A04_card_rotate.PNG',action:'rotate'},{id:'A02',label:'再看看示范图',img:'T02_A04_card_check_example.PNG',action:'check'},{id:'A03',label:'请泡泡狗帮忙',img:'T02_A04_card_ask_dog.PNG',action:'ask'},{id:'A04',label:'离开',img:'T02_A04_card_leave.PNG',action:'leave'}],x=>{stopAChoiceAudio();hide(ui.cards);if(x.action==='rotate'){rotatePiece(aState.piece,true);ui.prompt.textContent='现在可以继续试一试。'}else if(x.action==='check')ui.prompt.textContent='再看看左上角的示范图。';else{session.A_score=session.T02_A_score=0;completeA(false)}});narrateCards(questionAudio)}
  function completeA(ok=true){if(session.A_complete)return;stopAChoiceAudio();clearTimers();session.A_complete=ok;session.A_completion_time=Math.round(performance.now()-sceneStart);if(session.A_score===null)session.A_score=session.T02_A_score=ok?(session.A_hint_level<=1?2:1):0;currentCondition='A_COMPLETE';persist();ui.prompt.textContent='小鱼完成啦，我们看看下一个挑战。';log('scene_complete',{score:session.A_score});const bReady=preloadImage('T02_B01_windmill_interaction_base.png');video('T02_A05_fish_complete.mp4','T02_A05_fish_complete_end.png',()=>later(async()=>{await bReady;startB()},1400))}
  function startB(){currentCondition='B_P0';scene('T02_B01_windmill_interaction_base.png','把风车装完整。','情境 B · 四叶风车','2 / 2');audio('T02_B01_windmill_goal.mp3');const box=document.createElement('button'),slot=document.createElement('button');box.className=slot.className='tap-zone';box.ariaLabel='查看材料盒';slot.ariaLabel='查看风车空位';box.style.cssText='left:69%;top:47%;width:21%;height:28%';slot.style.cssText='left:43%;top:32%;width:18%;height:28%';box.onclick=()=>{session.B_check_material=true;log('check_material')};slot.onclick=()=>log('check_empty_slot');ui.overlay.append(box,slot);bState={asked:false,p1:false,p2:false,resolved:false,voiceCollected:false,pictureShown:false,problemQuestionAsked:false,presentingChoices:false,choicesNarrated:false,wrongChoiceCount:0,uncertainAttempts:0,voiceFallbackTimer:null,p1Timer:null,p2Timer:null};later(askB,6000);bState.p1Timer=later(()=>{if(!session.B_complete&&!bState.p1&&!bState.resolved)hintB1()},20000)}
  function showDock(mode='voice'){show(ui.dock);show(ui.voice);if(mode==='both')show(ui.picture);else hide(ui.picture);ui.voice.onclick=toggleMic;ui.picture.onclick=showBChoices}
  function revealPicture(){if(!bState||bState.pictureShown||bState.recording||bState.aiProcessing)return;bState.pictureShown=true;showDock('both');log('picture_fallback_shown')}
  function voiceFallbackCheck(){if(!bState||bState.voiceCollected||bState.pictureShown||bState.recording||bState.aiProcessing)return;ui.voiceStatus.textContent='还没有收到语音，你也可以用图片回答。';ui.prompt.textContent='还没有收到语音，你也可以用图片回答。';tone();later(revealPicture,1600)}
  function askB(){if(!bState.asked){bState.asked=true;ui.prompt.textContent='发生了什么？你需要什么？';audio('T02_B02_question.mp3');log('expression_prompt')}showDock('voice');ui.voiceStatus.textContent='请点击“说一说”开始录音';bState.voiceFallbackTimer=later(voiceFallbackCheck,7000)}
  async function showBChoices(){if(!bState||bState.resolved||bState.presentingChoices)return;if(!ui.cards.classList.contains('hidden')&&bState.choicesNarrated)return;bState.presentingChoices=true;clearTimeout(bState.voiceFallbackTimer);clearTimeout(bState.p1Timer);clearTimeout(bState.p2Timer);stopBChoiceAudio();currentCondition=currentCondition.startsWith('B_P')?currentCondition:'B_P0';ui.prompt.textContent='现在遇到了什么问题？';cards([{id:'B02',label:'方向不对',img:'T02_B04_problem_wrong_direction.PNG',kind:'direction'},{id:'B01',label:'少一个材料',img:'T02_B04_problem_missing_material.PNG',kind:'missing'},{id:'B04',label:'已经完成',img:'T02_B04_problem_completed.PNG',kind:'completed'},{id:'B03',label:'不知道',img:'T02_B04_problem_unknown.PNG',kind:'unknown'}],pickB);bState.presentingChoices=false;if(!bState.choicesNarrated){bState.problemQuestionAsked=true;bState.choicesNarrated=true;log('picture_problem_question');narrateBCombined(++bNarrationToken)}}
  async function narrateBCombined(token){const clip=bNarrationAudio=audio('T02_B04_problem_options.mp3');await new Promise(ok=>{if(clip.readyState>=1)ok();else{clip.addEventListener('loadedmetadata',ok,{once:true});clip.addEventListener('error',ok,{once:true});later(ok,1800)}});if(token!==bNarrationToken)return;const duration=Number.isFinite(clip.duration)&&clip.duration>2?clip.duration:13,intro=Math.min(3.2,duration*.26),segment=Math.max(1,(duration-intro)/4);await new Promise(ok=>later(ok,intro*1000));for(let i=0;i<4;i++){if(token!==bNarrationToken||ui.cards.classList.contains('hidden'))break;ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'));ui.cards.querySelector(`[data-index="${i}"]`)?.classList.add('speaking');await new Promise(ok=>later(ok,segment*1000))}ui.cards.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'));if(bNarrationAudio===clip)bNarrationAudio=null}
  function retryOrEndB(kind){if(!bState||bState.resolved)return;bState.wrongChoiceCount++;session.B_identify_missing=false;log('incorrect_problem_choice',{kind,attempt:bState.wrongChoiceCount});if(bState.wrongChoiceCount>=2){finishBUnresolved(`unresolved_after_two_answers:${kind}`);return}bState.p1=true;session.B_hint_level=Math.max(session.B_hint_level,1);ui.prompt.textContent='风车还没有完整，再看看风车和材料盒。';hide(ui.dock);audio('T02_B03_P1_instruction.mp3');clearTimeout(bState.p2Timer);bState.p2Timer=later(()=>{if(bState.resolved)return;bState.p2=true;session.B_hint_level=2;currentCondition='B_P2';ui.prompt.textContent='哪一张更像现在的问题？';showDock('both');showBChoices();persist()},3200)}
  function pickB(x){if(!bState||bState.resolved)return;stopBChoiceAudio();hide(ui.cards);const decision=T02VoicePolicy.routePicture({kind:x.kind,wrongAttempts:bState.wrongChoiceCount});if(decision.kind==='provide_piece'){session.B_help_request=true;session.B_identify_missing=true;session.B_help_specificity=2;persist();provideLeaf()}else if(decision.kind==='retry'){retryOrEndB(decision.reason)}else if(decision.kind==='finish_zero'){finishBUnresolved(decision.reason)}else{log('picture_manual_review',{kind:x.kind});showDock('both')}persist()}
  function hintB1(){if(bState.p1||session.B_complete||bState.recording||bState.aiProcessing)return;stopBChoiceAudio();bState.p1=true;currentCondition='B_P1';session.B_hint_level=1;ui.prompt.textContent='风车还没完整。再看看材料和空的位置。';audio('T02_B03_P1_instruction.mp3');log('hint',{level:1});showDock('both');bState.p2Timer=later(()=>{if(!session.B_complete&&!bState.p2&&!bState.recording&&!bState.aiProcessing)hintB2()},8000)}
  function hintB2(){if(bState.p2||session.B_complete||bState.recording||bState.aiProcessing)return;bState.p2=true;currentCondition='B_P2';session.B_hint_level=2;ui.prompt.textContent='哪一张更像现在的问题？';log('hint',{level:2});showDock('both');showBChoices()}
  function provideLeaf(){if(!bState||bState.resolved)return;bState.resolved=true;clearTimers();stopBChoiceAudio();currentCondition='B_SUPPORT';session.B_help_request=true;persist();hide(ui.cards);hide(ui.dock);ui.prompt.textContent='这里好像有一片叶子。';scene('T02_B05_leaf_drag_base.png','这里好像有一片叶子。','情境 B · 四叶风车','2 / 2');audio('T02_B05_leaf_on_table.mp3');later(leafDrag,700)}
  function leafDrag(){const piece=document.createElement('img'),target=document.createElement('div');piece.src=src('T02_B05_leaf_drag_piece.PNG');piece.className='drag-piece leaf-appear';piece.style.cssText='width:14%;left:61%;top:55%';target.style.cssText='position:absolute;left:41%;top:29%;width:20%;height:31%';ui.overlay.append(target,piece);pointerDrag(piece,{left:'61%',top:'55%'},(el,back)=>{if(hits(el,target)){el.style.left='45%';el.style.top='34%';completeB()}else back()});later(()=>piece.classList.remove('leaf-appear'),900);ui.prompt.textContent='把叶子装上。'}
  function completeB(){clearTimers();session.B_complete=true;session.B_score=session.T02_B_score=session.B_hint_level<=1?(session.B_identify_missing&&session.B_help_specificity===2?2:1):1;session.T02_total_score=(session.A_score+session.B_score)/2;persist();currentCondition='B_COMPLETE';log('scene_complete',{score:session.B_score});scene('T02_B05_windmill_complete_end.png','风车完成了。','T02 完成','2 / 2');later(finish,1400)}
  function finishBVagueAfterFollowup(){if(!bState||bState.resolved)return;bState.resolved=true;clearTimers();stopBChoiceAudio();session.B_complete=false;session.B_identify_missing=false;session.B_help_request=true;session.B_help_specificity=1;session.B_score=session.T02_B_score=1;session.T02_total_score=(session.A_score+session.B_score)/2;currentCondition='B_COMPLETE';log('scene_complete',{score:1,outcome:'vague_after_neutral_followup'});persist();scene('T02_B01_windmill_interaction_base.png','T02完成，谢谢你的参与。','T02 完成','2 / 2');later(finish,1400)}
  function finishBManualReview(reason='uncertain_audio_after_retry'){if(!bState||bState.resolved)return;bState.resolved=true;clearTimers();stopBChoiceAudio();session.B_complete=false;session.B_score=session.T02_B_score=null;session.T02_total_score=null;session.B_needs_review=true;session.validity='REVIEW';currentCondition='B_MANUAL_REVIEW';log('scene_complete',{score:null,outcome:'manual_review',reason});persist();scene('T02_B01_windmill_interaction_base.png','T02完成，谢谢你的参与。','T02 完成','2 / 2');later(finish,1400)}
  function finishBUnresolved(outcome='unresolved_after_two_choices',options={}){if(!bState||bState.resolved)return;bState.resolved=true;clearTimers();stopBChoiceAudio();session.B_complete=false;session.B_identify_missing=false;session.B_help_request=Boolean(options.helpRequest);session.B_help_specificity=Number(options.helpSpecificity||0);session.B_hint_level=Math.max(session.B_hint_level,2);session.B_score=session.T02_B_score=0;session.T02_total_score=(session.A_score+session.B_score)/2;currentCondition='B_COMPLETE';log('scene_complete',{score:0,outcome});persist();scene('T02_B01_windmill_interaction_base.png','T02完成，谢谢你的参与。','T02 完成','2 / 2');later(finish,1400)}
  function finish(){hide(ui.stage);show(ui.result);persist();window.parent.postMessage({source:'sel-task',type:'TASK_COMPLETE',taskId:'T02',result:session},'*')}
  function stopDebug(){session.validity='INV';session.T02_total_score=null;log('debug_stop');finish()}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();later(()=>URL.revokeObjectURL(a.href),3000)}
  function exportJSON(){const out={...session,B_choice:[...session.choices].reverse().find(x=>x.condition.startsWith('B'))?.choice_content??null,T02_score:session.T02_total_score};download(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),`${session.child_id}_T02_${Date.now()}.json`)}
  async function exportAudio(){const d=await database(),tx=d.transaction('audio'),r=tx.objectStore('audio').getAll();r.onsuccess=()=>r.result.filter(a=>session.speech_records.some(s=>s.audio_file===a.audio_file)).forEach((a,i)=>later(()=>download(a.blob,a.audio_file),i*250))}
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function loadReviews(){show(ui.research);ui.reviewList.textContent='正在加载……';try{const response=await fetch('/api/t02/reviews',{cache:'no-store'}),records=await response.json();ui.reviewList.innerHTML=records.length?records.map(r=>`<article class="review-card" data-review-id="${escapeHtml(r.id)}"><div class="review-grid"><div><strong>被试 / 会话</strong>${escapeHtml(r.participant_id)} / ${escapeHtml(r.session_id)}</div><div><strong>时间 / 提示等级</strong>${escapeHtml(r.created_at)} / P${escapeHtml(r.prompt_level)}</div><div><strong>模型转写</strong>${escapeHtml(r.model_transcript||'—')}</div><div><strong>语义理解</strong>${escapeHtml(r.semantic_summary||'—')}</div><div><strong>AI分类 / 分数</strong>${escapeHtml(r.ai_category)} / ${escapeHtml(r.ai_score)}</div><div><strong>置信度 / 下一分支</strong>${escapeHtml(r.ai_confidence)} / ${escapeHtml(r.next_action)}</div><div><strong>AI理由</strong>${escapeHtml(r.ai_reason||'—')}</div><div><strong>API状态</strong>${r.api_success?'成功':'失败：'+escapeHtml(r.api_error||'未知')}</div></div>${r.audio_file_path?`<audio controls src="/${escapeHtml(r.audio_file_path)}"></audio>`:'<p>无可播放录音</p>'}<div class="review-form"><label>人工分数</label><select data-human-score><option value="">未填写</option><option value="0" ${r.human_score===0?'selected':''}>0</option><option value="1" ${r.human_score===1?'selected':''}>1</option><option value="2" ${r.human_score===2?'selected':''}>2</option></select><label>人工分类</label><select data-human-category><option value="">未填写</option>${['missing_required_piece','vague_difficulty','request_adult_complete','irrelevant','dont_know','uncertain_audio'].map(x=>`<option value="${x}" ${r.human_category===x?'selected':''}>${x}</option>`).join('')}</select><label>人工备注</label><textarea data-human-note>${escapeHtml(r.human_note||'')}</textarea><span></span><button data-save-review>保存人工复核</button></div></article>`).join(''):'<p>暂无语音记录。</p>';ui.reviewList.querySelectorAll('[data-save-review]').forEach(button=>button.onclick=saveReview)}catch(e){ui.reviewList.textContent=`无法加载复核数据：${e.message}`}}
  async function saveReview(event){const card=event.currentTarget.closest('[data-review-id]'),id=card.dataset.reviewId,body={human_score:card.querySelector('[data-human-score]').value,human_category:card.querySelector('[data-human-category]').value,human_note:card.querySelector('[data-human-note]').value};event.currentTarget.disabled=true;try{const response=await fetch(`/api/t02/reviews/${encodeURIComponent(id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`server_${response.status}`);event.currentTarget.textContent='已保存'}catch(e){event.currentTarget.textContent='保存失败'}finally{event.currentTarget.disabled=false}}
  $('startBtn').onclick=()=>{session=fresh();persist();intro()};ui.mic.onclick=toggleMic;$('stopBtn').onclick=stopDebug;$('exportBtn').onclick=exportJSON;$('audioBtn').onclick=exportAudio;$('reviewBtn').onclick=loadReviews;$('refreshReviews').onclick=loadReviews;$('closeReviews').onclick=()=>hide(ui.research);$('restartBtn').onclick=()=>location.reload();document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='s')show($('stopBtn'));if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='r')loadReviews()});
})();
